Repository dchbx/enroll, pull requests merged in 2018-11, with the labels that each got.

#2412 37344: Failing Cucumbers in master
  features/support/worlds/ivl_assistance_world.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#2417 37377: Correct IVL Query For New States Introduced by Enrolled Contingent
  app/models/queries/ivl_enrollments_query.rb
  script/ivl_sep_query.rb
  spec/models/queries/ivl_enrollments_query_spec.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Hot Fix

#2360 29856: Plan Year display issue
  app/models/employer_profile.rb
  spec/models/employer_profile_spec.rb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#2414 37139: MEDICAL NEED: Employee Cannot Access Account due to Error Msg
  app/data_migrations/change_enrollment_details.rb
  lib/tasks/migrations/change_enrollment_details.rake
  spec/data_migrations/change_enrollment_details_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#2313 29207: All POC Staff for SHOP Employers
  script/er_poc_report.rb
Labels: Priority: Normal, Status: Accepted Pending Release, Status: Pending Deployment, Tracker: Data

#2411 37311: Error loading 2019 dental plan document
  db/seedfiles/plans-sbcs.csv
  plans-sbcs.csv
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: App-Dev_Use Case

#2053 21418: Eligibility engine accepts 'nil' value for 'Incarcerated' question for accounts impacted by previous UI bug
  app/models/insured_eligible_for_benefit_rule.rb
  spec/models/insured_eligible_for_benefit_rule_spec.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#2406 36785: Congressional Open Enrollment - Set the Open Enrollment Period Dates
  app/models/factories/family_enrollment_renewal_factory.rb
  spec/models/factories/family_enrollment_renewal_factory_spec.rb
Labels: Priority: Urgent, Status: Accepted Pending Release, Tracker: Support

#2430 37524: API Plan Match (Age When Coverage Begins)
  app/models/services/checkbook_services.rb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Bug
