Repository dchbx/enroll, pull requests merged in 2018-04, with the labels that each got.

#1962 21255: er_roster_report additions
  lib/tasks/hbx_reports/employer_roster_report.rake
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Support

#2106 23283: Footer and should reflect DC changes on PVT env.
  config/settings.yml
Labels: Mergeable: No, Priority: High, Status: Promote to Test Environment, Tracker: Code Refactor

#2089 22343: Unable to utilize manage family tab in EA for HBX:175668
  app/views/insured/family_members/_dependent_coverall.html.erb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Hot Fix

#2131 23653: Signup URL redirecting to Wrong page
  app/controllers/insured/employee_roles_controller.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#2139 22830: Demo Mock Eligibility
  app/controllers/financial_assistance/applications_controller.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Peer Review, Tracker: App-Dev_User Story

#2066 22843: Upload Termination Notice to Employer Secured Message Inbox in EA- March 2018 (3-6-2018)
  lib/tasks/upload_notice_for_employers.rake
Labels: Priority: Immediate, Status: Accepted Pending Release, Tracker: Trading Partner Data

#2148 23788: Relationship Structure in CV Incorrect
  app/views/events/individuals/_individual.xml.haml
Labels: Mergeable: Yes, Priority: Immediate, Status: Peer Review, Tracker: Code Refactor

#2074 22754: Retro Report Generation - February
  lib/tasks/verification_reports/verified_verification_reports.rake
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: App-Dev_User Story

#2073 22234: Outstanding verification due date missing
  app/data_migrations/invoke_hub_response.rb
  lib/tasks/invoke_hub_response.rake
  spec/data_migrations/invoke_hub_response_spec.rb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug

#1576 18207: We're sorry error when trying to terminate IVL plan using plan badge
  app/helpers/insured/group_selection_helper.rb
  spec/helpers/insured/group_selection_helper_spec.rb
Labels: Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#2143 23712: Investigate - Employees receiving error message when attempting to enroll in 5/1 coverage
  app/data_migrations/change_date_of_hire.rb
  lib/tasks/change_date_of_hire.rake
  spec/data_migrations/change_date_of_hire_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#1240 16390: Remove invoice available message for initial invoice
  app/invoices/employer_invoice.rb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Bug
