Repository dchbx/enroll, pull requests merged in 2018-06, with the labels that each got.

#2197 24372: Refactor of conversion scripts
  app/data_migrations/add_coverage_household_member.rb
  app/data_migrations/remove_consumer_role.rb
  app/models/importers/conversion_employee_action.rb
  app/models/importers/conversion_employee_common.rb
  app/models/importers/conversion_employee_create.rb
  app/models/importers/conversion_employer.rb
  app/models/importers/conversion_employer_create.rb
  app/models/importers/conversion_employer_set.rb
  app/models/importers/mhc/conversion_employer.rb
  app/models/importers/mhc/conversion_employer_create.rb
  app/models/importers/mhc/conversion_employer_set.rb
  app/models/importers/row_set.rb
  app/models/legacy_importers/shop_policy.rb
  app/models/special_enrollment_period.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/app/models/benefit_sponsors/concerns/employer_profile_concern.rb
  components/benefit_sponsors/app/models/benefit_sponsors/documents/employer_attestation.rb
  components/benefit_sponsors/app/models/benefit_sponsors/documents/employer_attestation_document.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employee_action.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employee_common.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employee_create.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/conversion_employer_carrier_value.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/mhc/conversion_employee_set.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/mhc/conversion_employer_create.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/mhc/conversion_employer_set.rb
  components/benefit_sponsors/script/import_conversion_employees.rb
  components/benefit_sponsors/script/import_conversion_employer.rb
  components/benefit_sponsors/spec/factories/benefit_sponsors_site.rb
  components/benefit_sponsors/spec/models/importers/mhc/conversion_employer_create_spec.rb
  lib/tasks/migrations/add_coverage_household_member.rake
  lib/tasks/migrations/remove_consumer_role.rake
  spec/data_migrations/add_coverage_household_member_spec.rb
  spec/data_migrations/remove_consumer_role_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: Feature

#2206 24064: Make checkboxes editable for broker accounts
  app/controllers/exchanges/broker_applicants_controller.rb
  app/models/broker_role.rb
  app/views/shared/brokers/_applicant.html.erb
  spec/controllers/exchanges/broker_applicants_controller_spec.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#2108 21522: FAA Cucumber: Income Adjustments (deductions)
  features/financial_assistance/income_adjustments_page.feature
  features/financial_assistance/step_definitions/income_adjustments_page_steps.rb
Labels: Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#2167 23450: Adjustments in FAA resulting in application submission failures
  app/views/events/financial_assistance/_deduction.xml.haml
  lib/schemas/individual.xsd
Labels: Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#2217 24787: Transmit Late Initial Group - Embassy of the Union of Myanmar
  app/data_migrations/fix_plan_year.rb
  spec/data_migrations/fix_plan_year_spec.rb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Critical Data

#2001 19000: Updates to IVL_PRE Notice- Projected Eligibility
  app/views/notices/ivl/projected_eligibility_notice.html.erb
Labels: Priority: High, Status: Accepted Pending Release, Tracker: Enhancement

#2158 23992: Enrollment ID Extension
  lib/tasks/verification_reports/verified_verification_reports.rake
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Enhancement

#2211 24048: Accounts Migration
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
  db/migrate/20180517172333_cca_broker_agency_accounts_migration.rb
  spec/migrations/cca_broker_agency_accounts_migration_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Peer Review, Tracker: App-Dev_Feature

#2075 21123: Monthly report of outstanding verifications
  lib/tasks/verification_reports/outstanding_verifications_created.rake
Labels: Mergeable: Yes, Priority: Normal, Status: Resolved, Tracker: App-Dev_Feature

#2210 24416: EE Not Linked to Roster - 19892737
  app/data_migrations/remove_coverage_household_member.rb
  lib/tasks/migrations/adding_employee_role.rake
  lib/tasks/migrations/remove_coverage_household_member.rake
  spec/data_migrations/remove_coverage_household_member_spec.rb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Hot Fix

#1954 21097: Spacing in signature line in Reminder Notices
  app/views/notices/ivl/documents_verification_reminder.html.erb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug
