Repository dchbx/enroll, pull requests merged in 2018-09, with the labels that each got.

#2330 29789: SEP effective date rules not working
  app/controllers/insured/families_controller.rb
  app/models/hbx_enrollment.rb
  app/views/insured/families/_shop_for_plans_widget.html.erb
  spec/controllers/insured/families_controller_spec.rb
  spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Bug

#2082 21777: Res Party Enrollment won't flow from EA to Glue
  script/ivl_sep_query.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Bug

#2347 30827: Large employers time-out during the renewal process in DC
  app/models/factories/employer_open_enrollment_factory.rb
Labels: Priority: Urgent, Status: Promote to Test Environment, Tracker: Bug

#2281 27644: Need to reping hub when citizenship in verified state is updated to no citizenship with eligible immigration status
  app/controllers/concerns/vlp_doc.rb
  app/controllers/insured/family_members_controller.rb
  app/controllers/people_controller.rb
  app/models/consumer_role.rb
  spec/controllers/concerns/vlp_doc_spec.rb
  spec/models/consumer_role_spec.rb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: App-Dev_Use Case

#2351 30638: Supplement to Ticket #30152
  app/data_migrations/fix_plan_year.rb
  spec/data_migrations/fix_plan_year_spec.rb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Critical Data

#2285 27045: Streamline and Automate NFP Passive Renewal Process
  script/force_publish_plan_years.rb
  script/policies_for_employer_ies.rb
  script/policies_for_employer_renewals.rb
  script/policies_for_simulated_renewals.rb
Labels: Priority: Urgent, Status: Pending Deployment, Tracker: Code Refactor
