Repository dchbx/enroll, pull requests merged in 2018-05, with the labels that each got.

#2060 19929: Former broker has access to terminated employees account
  app/controllers/employers/employer_profiles_controller.rb
  spec/controllers/employers/employer_profiles_controller_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#2176 24177: "Is living in State" attribute should be defaulted to false
  app/models/financial_assistance/applicant.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: Code Refactor

#2180 24180: CoverAll DC Part 2 - Update person roles in UI According to family Transition changes
  app/helpers/exchanges/hbx_profiles_helper.rb
  app/models/effective/datatables/family_data_table.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#2186 24305: Sending Invitations to renewal employees, initial employees and active employees
  app/models/plan_year.rb
  app/models/subscribers/employee_enrollment_invitations_subscriber.rb
  app/models/subscribers/employee_initial_enrollment_invitations_subscriber.rb
  app/models/subscribers/employee_renewal_invitations_subscriber.rb
  app/models/user.rb
  config/application.rb
  spec/models/plan_year_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: App-Dev_Use Case

#2184 23945: SSN Removal/Change
  lib/tasks/migrations/updating_person_ssn.rake
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Critical Data

#2191 24357: Refactor HAML file
  app/views/events/individuals/_person.xml.haml
Labels: Mergeable: Yes, Priority: Immediate, Status: Peer Review, Tracker: Enhancement

#2123 23443: Wrong adjustment type in error message
  app/assets/javascripts/financial_assistance/deduction.js
  app/views/financial_assistance/deductions/index.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: Code Refactor

#1803 19935: Transition 12/1 groups to Renewing_enrolled
  app/models/plan_year.rb
  config/settings.yml
  spec/models/plan_year_spec.rb
Labels: Mergeable: No, Priority: Urgent, Status: Accepted Pending Release, Tracker: Critical Data

#2200 24112: 500 Error before Plan Shopping
  app/controllers/insured/plan_shoppings_controller.rb
Labels: Assignee: Joshua Karper, Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: App-Dev_User Story
