Repository dchbx/enroll, pull requests merged in 2018-07, with the labels that each got.

#2243 25579: Update scripts for NFP Provisional Passive renewals to accommodate new model changes
  app/models/queries/named_enrollment_queries.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  script/force_publish_benefit_applications.rb
  script/policies_for_employer_ies.rb
  script/policies_for_employer_renewals.rb
  script/policies_for_simulated_renewals.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Peer Review, Tracker: Use Case

#1983 21157: Extend 2/1 OE plan shopping deadline through 1/17 (individual market)
  app/models/hbx_profile.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Resolved, Tracker: Support

#2212 23706: Investigate - EE showing as not linked when linked
  app/data_migrations/change_census_employee_details.rb
  lib/tasks/change_census_employee_details.rake
  spec/data_migrations/change_census_employee_details_spec.rb
Labels: Priority: High, Status: Pending Deployment, Tracker: Bug

#2168 23469: Person is blocked from claiming user
  app/data_migrations/update_curam_user_records.rb
  lib/tasks/update_curam_user_records.rake
  spec/data_migrations/update_curam_user_records_spec.rb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Data

#1558 17976: Additional fields needed for report of all verifications
  lib/tasks/hbx_reports/outstanding_documents_report.rake
Labels: Priority: Normal, Status: Pending Deployment, Tracker: App-Dev_Feature

#2249 25964: Refactor - Broker Magic URL Report
  lib/tasks/hbx_reports/brokers_with_URL_from_admin_approval.rake
Labels: Assignee: Vishal Kalletla, Mergeable: Yes, Priority: Urgent, Status: BA Review, Tracker: Feature

#2247 25966: Refactor POC Pending Report
  lib/tasks/hbx_reports/employer_poc_pending_report.rake
Labels: Mergeable: Yes, Priority: Urgent, Status: BA Review, Tracker: Feature

#2270 27376: Documents with due dates in review status should show this due date for the family
  app/helpers/verification_helper.rb
  features/step_definitions/verification_process_steps.rb
  spec/helpers/verification_helper_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Peer Review, Tracker: App-Dev_User Story

#2269 27289: Residency verification placed in processing status when SSA hub re-pinged for child
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: App-Dev_Use Case

#2259 26340: "View History" is not displaying mock response for DC Residency.
  app/models/subscribers/local_residency.rb
  spec/models/subscribers/local_residency_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#2272 27307: Employer/Employee Unable to View Employee Census Details from Roster (Reverse Data Migration from Glue Needed)- Embassy of the Union of Myanmar
  app/models/importers/transcripts/enrollment_transcript.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Bug
