Repository dchbx/enroll, pull requests merged in 2018-03, with the labels that each got.

#2059 21291: Text changes for voter registration in FAA
  app/views/financial_assistance/applications/steps.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: Bug

#2030 22258: Unable to Remove Duplicate Family Member
  app/data_migrations/remove_dependent.rb
  spec/data_migrations/remove_dependent_spec.rb
  spec/factories/families.rb
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Bug

#2037 22118: Critical CareFirst "Plus" Plan Network Update Needed - Nationwide to DC Metro
  lib/tasks/hbx_reports/families_with_invalid_plan.rake
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Critical Data

#1805 13216: Exchange ID is incorrect in the enrollment_event resource xml
  app/views/events/enrollment_event.xml.haml
  config/settings.yml
Labels: Mergeable: No, Priority: Urgent, Status: Stakeholder Review, Tracker: Bug

#1684 18750: ActionView::MissingTemplate (Missing template employers/broker_agency/index, application/index with
  app/controllers/employers/broker_agency_controller.rb
  spec/controllers/employers/broker_agency_controller_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#1944 19840: Can't see full e-case ID and person role for Curam cases in EA families tab
  app/views/exchanges/hbx_profiles/_get_user_info.html.erb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#2022 22134: Date format on verifications tab changes after searching
  app/models/effective/datatables/outstanding_verification_data_table.rb
Labels: Priority: High, Status: Accepted Pending Release, Tracker: Bug

#2039 22310: Minor text changed needed to Documents Needed insert
  app/views/notices/ivl/documents_section.html.erb
Labels: Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#2095 23008: Homeless/Temporarily Out of State Model Update
  app/controllers/exchanges/residents_controller.rb
  app/controllers/insured/consumer_roles_controller.rb
  app/controllers/insured/families_controller.rb
  app/controllers/people_controller.rb
  app/data_migrations/change_incorrect_bookmark_url_in_consumer_role.rb
  app/models/forms/family_member.rb
  app/models/importers/transcripts/person_transcript.rb
  app/models/person.rb
  app/models/transcripts/comparison_result.rb
  app/models/transcripts/person_transcript.rb
  app/notices/ivl_notices/final_eligibility_notice_renewal_uqhp.rb
  app/notices/ivl_notices/final_eligibility_notice_uqhp.rb
  app/views/shared/_address_fields_for_dependent.html.erb
  app/views/shared/_consumer_home_address_fields.html.erb
  app/views/shared/_resident_home_address_fields.html.erb
  spec/controllers/insured/families_controller_spec.rb
  spec/models/forms/family_member_spec.rb
  spec/models/person_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: Code Refactor

#2085 22988: APTC Availability
  app/data_migrations/add_family_member_to_coverage_household.rb
  lib/tasks/migrations/add_family_member_to_coverage_household.rake
  spec/data_migrations/add_family_member_to_coverage_household_spec.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Critical Data

#2114 23286: Unable to uncheck checkboxes in FAA branch
  app/assets/javascripts/financial_assistance/income.js
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: App-Dev_User Story

#2027 22136: Outstanding verification item for immigration showing under 'fully uploaded' tab on the verification page
  app/controllers/documents_controller.rb
  app/data_migrations/fix_document_status_on_family.rb
  app/views/insured/families/verification/_verification.html.erb
  lib/tasks/fix_document_status_on_family.rake
  spec/controllers/documents_controller_spec.rb
  spec/data_migrations/fix_document_status_on_family_spec.rb
Labels: Mergeable: Yes, Priority: High, Status: Accepted Pending Release, Tracker: Bug

#2094 23066: Seeding Fails in Master
  config/settings.yml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to UAT, Tracker: Code Refactor

#2026 20572: When click on delete Icon in Documents screen of a user's account not updating in view history
  app/views/documents/destroy.js.erb
  app/views/insured/families/verification/_verification.html.erb
Labels: Mergeable: No, Priority: Immediate, Status: Pending Deployment, Tracker: Enhancement
