Repository dchbx/enroll, pull requests merged in 2018-02, with the labels that each got.

#2017 21292: Text change to tax info page
  app/views/financial_assistance/applicants/steps.yml
  app/views/financial_assistance/applications/review_and_submit.html.erb
  app/views/financial_assistance/applications/steps_backup.yml
  app/views/financial_assistance/shared/support_text.yml
  components/ui_helpers/spec/dummy/app/views/surveys/steps.yml
Labels: Mergeable: Yes, Priority: High, Status: Peer Review, Tracker: Bug

#1932 20897: Report of all cases impacted by ENR notice not populating citizenship documentation requirement (bug 20845)
  script/enrollment_affected_people.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Bug

#2029 22301: Conditional Transmission of FAA fields.
  app/views/events/financial_assistance/_applicant_information.xml.haml
  app/views/events/financial_assistance/_benefit.xml.haml
  app/views/events/financial_assistance/_income.xml.haml
  app/views/events/financial_assistance_application.xml.haml
Labels: Mergeable: Yes, Priority: High, Status: Peer Review, Tracker: Bug

#1927 20944: Report of all users with resident role
  script/get_resident_enrollments_in_ea.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Critical Data

#1933 20900: Report of cases where Citizenship document type not populated in docs need in Reminder Notice
  script/reminder_notice_issue.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Pending Deployment, Tracker: Support

#2031 21993: Remove duplicate "Help me sign up" on identity/app doc upload page
  app/views/insured/interactive_identity_verifications/failed_validation.html.haml
Labels: Priority: Urgent, Status: Peer Review, Tracker: Bug

#2014 22146: Modify Eligibility Creation Task to not consider inactive FamilyMembers when creating THHMs
  app/models/family.rb
  app/models/household.rb
  spec/models/family_spec.rb
Labels: Mergeable: No, Priority: Immediate, Status: Pending Deployment, Tracker: Critical Data
