Repository dchbx/enroll, pull requests merged in 2018-08, with the labels that each got.

#2287 26028: Refactor IVL_CDC and IVL_DCH to consider Verifications Refactor
  app/notices/ivl_notices/ivl_to_coverall_transition_notice_builder.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#2289 27963: Auto-renewal Issue for EEs of Renewal Groups with >20 EEs on Roster
  app/data_migrations/create_renewal_plan_year_and_enrollment.rb
  spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#2293 28830: Modify Active Renewal Job
  app/models/plan_year.rb
  app/models/subscribers/employee_passive_renewals_subscriber.rb
  config/application.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Accepted Pending Release, Tracker: Bug

#2300 29091: SPEC failure for, Bug #28830
  spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb
  spec/data_migrations/triggering_auto_renewals_for_specific_employer_spec.rb
  spec/data_migrations/triggering_auto_renewals_spec.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Bug

#2304 25677: Please hide the First Time Applications for Medicaid and Premium Tax Credits tab in the HBX EA prod Broker Agency menu
  app/views/broker_agencies/profiles/_menu.html.erb
  spec/views/broker_agencies/profiles/_menu.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: Bug

#2324 27310: Refactor Monthly report outstanding verifications
  lib/tasks/verification_reports/outstanding_verifications_created.rake
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: App-Dev_Feature

#2320 25394: Pay Now Kaiser-Language Update on “How to Pay” button on “Enrollment Submitted” page-update will only be visible for IVL/Cover All initial Kaiser plan enrollments
  app/views/insured/plan_shoppings/receipt.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#2280 21289: Not able to continue with single instance of ESI
  app/views/financial_assistance/benefits/_esi_benefit_form.html.erb
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: App-Dev_User Story
