Repository dchbx/enroll, pull requests merged in 2018-12, with the labels that each got.

#2476 38554: Extend 1/1 effective date plan shopping for IVL
  app/models/hbx_profile.rb
  config/settings.yml
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support

#2473 38270: Unable to reinstate employers in termination pending state
  app/data_migrations/reinstate_plan_year.rb
  app/models/plan_year.rb
  spec/data_migrations/reinstate_plan_year_spec.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Accepted Pending Release, Tracker: Bug

#2486 38523: Gaining access to House consumer's account in EA HBX Member ID: 1728381
  app/data_migrations/update_hbx_enrollment_employee_role_id.rb
  lib/tasks/migrations/update_hbx_enrollment_employee_id.rake
  spec/data_migrations/update_hbx_enrollment_employee_role_id_spec.rb
Labels: Priority: Immediate, Status: Pending Deployment, Tracker: Data
