Repository dchbx/enroll, pull requests merged in 2019-10, with the labels that each got.

#3199 40036
  app/controllers/insured/consumer_roles_controller.rb
  app/controllers/insured/family_members_controller.rb
  app/controllers/people_controller.rb
  app/models/hbx_staff_role.rb
  app/policies/consumer_role_policy.rb
  spec/controllers/insured/consumer_roles_controller/consumer_roles_controller_update_spec.rb
  spec/controllers/insured/consumer_roles_controller_spec.rb
  spec/controllers/insured/family_members_controller/family_members_controller_update_spec.rb
  spec/policies/consumer_role_policy_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3261 53893
  app/controllers/insured/consumer_roles_controller.rb
  spec/controllers/insured/consumer_roles_controller_spec.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3275 57639
  script/generate_employer_renewals.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Data

#3277 53910
  app/notices/ivl_notices/final_eligibility_notice_aqhp.rb
  app/notices/ivl_notices/final_eligibility_notice_uqhp.rb
  app/views/notices/ivl/final_eligibility_notice_aqhp.html.erb
  app/views/notices/ivl/final_eligibility_notice_uqhp.html.erb
  app/views/notices/shared/_oe_dates.html.erb
  script/ivl_renewal_notices.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Peer Review, Tracker: Support

#3290 59794
  app/controllers/insured/consumer_roles_controller.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3291 43739
  app/assets/stylesheets/application.scss.erb
  app/views/people/landing_pages/_personal.html.erb
  app/views/shared/_consumer_home_address_fields.html.erb
  app/views/shared/_contact_preferences.html.erb
  app/views/shared/_home_address_fields.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3272 54170
  app/models/hbx_enrollment.rb
  app/models/plan_selection.rb
  spec/models/hbx_enrollment_spec.rb
  spec/models/plan_selection_spec.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3266 54169
  script/ivl_sep_query.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3262 43689
  app/models/hbx_enrollment.rb
  lib/tasks/renewal_state_change.rake
  spec/lib/tasks/renewal_state_change_spec.rb
  spec/models/enrollments/individual_market/open_enrollment_begin_spec.rb
  spec/shared_contexts/enrollment.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#3302 61132
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_application_eligibility_policy.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollment_service_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3295 42818
  app/views/shared/plan_shoppings/_more_plan_details.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3313 60856
  app/javascript/controllers/signup_controller.js
Labels: Assignee: Sri Harsha Poosa, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support
