Repository dchbx/enroll, pull requests merged in 2019-12, with the labels that each got.

#3318 62060
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/general_agency_profile.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/general_agency_profile_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3357 60911
  app/controllers/insured/families_controller.rb
  app/models/hbx_enrollment.rb
  spec/controllers/insured/families_controller_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3366 74148
  app/data_migrations/updating_broker_agency_account_or_profile.rb
  lib/tasks/migrations/updating_broker_agency_account_or_profile.rake
  spec/data_migrations/updating_broker_agency_account_or_profile_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3371 65666
  app/controllers/application_controller.rb
  app/controllers/insured/consumer_roles_controller.rb
  app/controllers/insured/families_controller.rb
  app/controllers/insured/family_members_controller.rb
  app/controllers/insured/plan_shoppings_controller.rb
  app/models/person.rb
  app/views/insured/interactive_identity_verifications/failed_validation.html.haml
  spec/controllers/application_controller_spec.rb
  spec/controllers/insured/consumer_roles_controller_spec.rb
  spec/models/person_spec.rb
  spec/views/insured/interactive_identity_verifications/failed_validation.html.haml_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3369 74479
  components/benefit_sponsors/app/policies/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller_policy.rb
  components/benefit_sponsors/spec/policies/profiles/broker_agencies/broker_agency_profiles_controller_policy_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3370 70182
  components/benefit_sponsors/app/helpers/benefit_sponsors/employers/employer_helper.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/_sponsored_benefit.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3373 77166
  features/employers/add_plan_year_for_employer.feature
  features/hbx_admin/step_definitions/create_plan_year.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Support

#3383 78952
  app/models/hbx_profile.rb
  config/settings.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3376 57464
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/employee_waiver_confirmation_spec.rb
  components/notifier/app/models/notifier/builders/employee_profile.rb
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3333 51916
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3245 43808
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/employee_open_enrollment_reminder_spec.rb
  components/notifier/app/models/notifier/builders/benefit_application.rb
Labels: Priority: 3-High, Status: In Progress, Tracker: Bug

#3382 78975
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_enrollments_monthly_query_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
  components/sponsored_benefits/spec/shared_contexts/sponsored_benefits.rb
  spec/data_migrations/update_employee_role_id_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/tasks/nfp_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Hot Fix

#3389 76834
  app/models/forms/family_member.rb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3368 53997
  app/notices/ivl_notices/final_eligibility_notice_renewal_aqhp.rb
  app/notices/ivl_notices/final_eligibility_notice_renewal_uqhp.rb
  app/views/notices/ivl/final_eligibility_notice_uqhp_aqhp.html.erb
  app/views/notices/shared/_enrollment_info_table.html.erb
  script/ivl_renewal_notices.rb
  spec/notices/ivl_notices/final_eligibility_notice_renewal_aqhp_spec.rb
  spec/notices/ivl_notices/final_eligibility_notice_renewal_uqhp_spec.rb
Labels: Assignee: NOT ASSIGNED, Mergeable: Yes, Priority: 4-Normal, Status: Closed, Tracker: Support

#3395 81213
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3402 80505
  features/step_definitions/group_selection_steps.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Support

#3404 74948
  script/correct_invalid_enrollments.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3398 81592
  app/views/user_mailer/dc_invite_initial_employee_for_open_enrollment.html.erb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug
