Repository dchbx/enroll, pull requests merged in 2019-11, with the labels that each got.

#3319 61886
  app/models/services/ivl_enrollment_renewal_service.rb
  spec/models/services/ivl_enrollment_renewal_service_spec.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3317 62101
  app/models/enrollments/individual_market/family_enrollment_renewal.rb
  spec/models/enrollments/individual_market/family_enrollment_renewal_spec.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3292 43484
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
Labels: Assignee: Bobby Jones, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3322 57922
  components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/dental_sponsored_benefit.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3328 65176
  app/models/effective/datatables/employee_datatable.rb
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3330 57913
  components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/dental_sponsored_benefit.rb
Labels: Assignee: Sri Harsha Poosa, Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3344 43371
  app/controllers/employers/employer_profiles_controller.rb
  spec/controllers/employers/employer_profiles_controller_spec.rb
Labels: Assignee: NOT ASSIGNED, Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3321 43362
  app/assets/stylesheets/custom.scss.erb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug
