Repository dchbx/enroll, pull requests merged in 2019-09, with the labels that each got.

#3233 47716
  config/webpack/production.js
  package.json
  yarn.lock
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#3234 47743
  app/models/factories/family_enrollment_clone_factory.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_enrollments_query.rb
  spec/models/factories/family_enrollment_clone_factory_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3226 43880
  components/notifier/app/models/notifier/builders/employer_profile.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3140 43472
  components/notifier/app/helpers/notifier/consumer_role_helper.rb
  components/notifier/app/models/notifier/builders/consumer_role.rb
  components/notifier/app/models/notifier/merge_data_models/consumer_role.rb
  components/notifier/app/models/notifier/notice_builder.rb
  components/notifier/app/models/notifier/services/dependent_service.rb
  components/notifier/app/views/layouts/notifier/_dc_cover_page.html.erb
  components/notifier/app/views/layouts/notifier/_dc_ivl_address.html.erb
  components/notifier/app/views/notifier/notice_kinds/ivl_template.html.erb
  spec/components/notifier/builders/consumer_role_spec.rb
  spec/components/notifier/builders/dependent_service_spec.rb
  spec/test_data/notices/proj_elig_report_aqhp_2019_test_data.csv
Labels: Assignee: NOT ASSIGNED, Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3241 46870
  lib/tasks/hbx_reports/newly_registered_persons_data_report.rake
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Data

#3247 51153
  app/views/exchanges/hbx_profiles/generate_invoice.js.erb
  app/views/exchanges/hbx_profiles/invoice.html.slim
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug
