Repository dchbx/enroll, pull requests merged in 2019-02, with the labels that each got.

#2522 39178
  app/data_migrations/add_consumer_role_for_family_member.rb
  lib/tasks/migrations/add_consumer_role_for_family_member.rake
  spec/data_migrations/add_consumer_role_for_family_member_spec.rb
Labels: Priority: High, Status: Pending Deployment, Tracker: Data

#2528 39728
  script/ea_user_roles_permission.rb
Labels: Priority: Urgent, Status: Promote to Test Environment, Tracker: Support

#2532 39767
  script/internal_access_accounts_report.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Promote to Test Environment, Tracker: Support

#2542 16918
  app/models/bill_file.rb
  lib/tasks/billfile_export.rake
Labels: Mergeable: Yes, Priority: High, Status: Promote to Test Environment, Tracker: App-Dev_Feature

#2544 38999
  script/enr_gen_family_id.rb
Labels: Mergeable: Yes, Priority: Urgent, Status: Functional Testing, Tracker: Bug

#2546 39232
  config/settings.yml
Labels: Priority: Normal, Status: Pending Deployment, Tracker: Support

#2540 39582
  app/data_migrations/change_renewing_plan_year_aasm_state.rb
  spec/data_migrations/app/change_renewing_plan_year_aasm_state_spec.rb
Labels: Mergeable: Yes, Priority: Immediate, Status: Accepted Pending Release, Tracker: Support

#2551 39911
  app/controllers/employers/census_employees_controller.rb
  app/controllers/employers/employer_profiles_controller.rb
  app/controllers/employers/plan_years_controller.rb
  app/controllers/exchanges/agents_controller.rb
  app/controllers/insured/families_controller.rb
  app/helpers/portal_header_helper.rb
  app/models/person.rb
  app/policies/family_policy.rb
  app/views/broker_agencies/profiles/_family_datatable_entry.json.erb
  spec/controllers/employers/employer_profiles_controller_spec.rb
  spec/controllers/employers/plan_years_controller_spec.rb
  spec/controllers/insured/families_controller_spec.rb
  spec/models/person_spec.rb
  spec/policies/family_policy_spec.rb
Labels: Mergeable: Yes, Priority: Normal, Status: Peer Review, Tracker: App-Dev_Use Case

#2549 39888
  app/models/consumer_role.rb
  app/models/lawful_presence_determination.rb
  spec/models/consumer_role_spec.rb
  spec/models/hbx_enrollment_spec.rb
  spec/models/lawful_presence_determination_spec.rb
  spec/test_data/lawful_presence_payloads/response2.xml
  spec/test_data/ssa_verification_payloads/response.xml
Labels: Mergeable: Yes, Priority: Normal, Status: Promote to Test Environment, Tracker: App-Dev_Feature
