Repository dchbx/enroll, pull requests merged in 2020-03, with the labels that each got.

#3485 85656
  app/controllers/exchanges/broker_applicants_controller.rb
  app/data_migrations/extend_broker_application.rb
  app/models/broker_role.rb
  app/models/person.rb
  app/views/shared/brokers/applicant.html.erb
  components/benefit_sponsors/app/models/benefit_sponsors/services/staff_role_reapplication_service.rb
  components/benefit_sponsors/spec/dummy/app/models/broker_role.rb
  components/benefit_sponsors/spec/dummy/app/models/general_agency_staff_role.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/staff_role_reapplication_service_spec.rb
  features/brokers/broker_reapplication.feature
  features/brokers/broker_registration.feature
  features/step_definitions/brokers_steps.rb
  features/support/worlds/broker_agency_world.rb
  lib/tasks/migrations/extend_broker_application.rake
  spec/controllers/exchanges/broker_applicants_controller_spec.rb
  spec/data_migrations/extend_broker_application_spec.rb
  spec/models/broker_role_spec.rb
Labels: Priority: 4-Normal, Status: Functional Testing, Tracker: App-Dev_User Story

#3332 65504
  app/models/queries/shop_monthly_enrollments.rb
  spec/models/queries/shop_monthly/monthly_quiet_period_enrollments_query_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3286 53855
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
  components/benefit_sponsors/spec/dummy/app/models/acapi/notifiers.rb
  components/benefit_sponsors/spec/dummy/app/models/concerns/config/aca_model_concern.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/scheduled_events/auto_transmit_monthly_benefit_sponsors_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3490 85702
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3471 85322
  components/benefit_sponsors/app/policies/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller_policy.rb
  components/benefit_sponsors/spec/policies/profiles/broker_agencies/broker_agency_profiles_controller_policy_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3495 85672
  app/data_migrations/add_family_member_to_coverage_household.rb
  spec/data_migrations/add_family_member_to_coverage_household_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3483 85630
  components/notifier/app/assets/javascripts/notifier/ckeditor/contents.css
  components/notifier/app/assets/javascripts/notifier/ckeditor/lang/en.js
  components/notifier/app/assets/javascripts/notifier/ckeditor/plugins/lineheight/plugin.js
  components/notifier/app/assets/javascripts/notifier/ckeditor/plugins/liststyle/dialogs/liststyle.js
  components/notifier/app/assets/javascripts/notifier/ckeditor/plugins/pastefromword/filter/default.js
  components/notifier/app/assets/javascripts/notifier/ckeditor/plugins/templates/templates/default.js
  components/notifier/app/assets/javascripts/notifier/ckeditor/styles.js
  components/notifier/app/models/notifier/notice_builder.rb
  components/notifier/app/views/layouts/notifier/application.html.erb
  components/notifier/app/views/layouts/notifier/ivl_pdf_layout.html.erb
  components/notifier/app/views/layouts/notifier/pdf_layout.html.erb
  components/notifier/spec/models/notifier/notice_builder_spec.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: App-Dev_Feature

#3499 85776
  lib/tasks/hbx_reports/employers.rake
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#3468 85218
  app/models/subscribers/policy_terminations_subscriber.rb
  script/shop_sep_query.rb
  spec/models/subscribers/policy_terminations_subscriber_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3491 42258
  app/assets/javascripts/demographics_fields.js
  components/benefit_sponsors/db/seedfiles/translations/en/insured.rb
  db/seedfiles/translations/en/insured.rb
Labels: Mergeable: Yes, Priority: 5-Low, Status: Accepted Pending Release, Tracker: Support

#3459 84997
  app/controllers/insured/group_selection_controller.rb
  app/models/group_selection_prevarication_adapter.rb
  spec/controllers/insured/group_selection_controller_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3489 85671
  app/models/family.rb
  app/models/hbx_enrollment.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/spec/dummy/app/models/family.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  spec/models/family_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3511 86139
  app/controllers/insured/group_selection_controller.rb
  spec/controllers/insured/group_selection_controller_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3477 37476
  app/controllers/exchanges/hbx_profiles_controller.rb
  spec/controllers/exchanges/hbx_profiles_controller_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3464 82275
  app/views/insured/consumer_roles/docs_shared/_i_94_number.html.erb
  db/seedfiles/translations/en/insured.rb
  features/insured/individual_vlp_verification.feature
  features/step_definitions/individual_steps.rb
Labels: Assignee: Kathlin Nicol, Priority: 4-Normal, Status: Stakeholder Review, Tracker: App-Dev_Feature

#3513 79348
  app/controllers/insured/group_selection_controller.rb
  app/models/family.rb
  spec/controllers/insured/group_selection_controller_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3524 42664
  components/benefit_markets/db/seedfiles/translations/en/insured.rb
  components/benefit_sponsors/db/seedfiles/translations/en/insured.rb
  db/seedfiles/translations/en/insured.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Promote to Test Environment, Tracker: Bug

#3500 85831
  script/shop_sep_query.rb
  spec/script/shop_sep_query_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Promote to Test Environment, Tracker: Bug

#3539 86536
  app/models/admin/aptc.rb
  app/models/insured/factories/self_service_factory.rb
  app/models/insured/forms/self_term_or_cancel_form.rb
  config/settings.yml
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/models/benefit_coverage_period_spec.rb
  spec/models/enrollment_period/special_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Functional Testing, Tracker: Support

#3525 40731
  app/helpers/config/contact_center_helper.rb
  app/views/ui-components/bs4/v1/footers/_footer.slim
  app/views/ui-components/bs4/v1/navs/_header.slim
  app/views/ui-components/v1/layouts/_footer.html.slim
  app/views/ui-components/v1/navs/_header.html.slim
  spec/views/ui-components/v1/layouts/_footer.html.slim_spec.rb
Labels: Mergeable: Yes, Priority: 5-Low, Status: Accepted Pending Release, Tracker: Code Refactor

#3348 43628
  app/views/exchanges/hbx_profiles/_new_benefit_application.html.slim
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_service.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
  features/hbx_admin/create_plan_year.feature
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3258 43629
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3526 84578
  app/models/family.rb
  components/benefit_sponsors/spec/dummy/app/models/family.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3505 86240
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/plan_design_organization.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_indexes_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/plan_design_organization_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Code Refactor

#3305 61673
  app/data_migrations/force_publish_ben_app_reports.rb
  lib/tasks/force_publish_ben_app_reports.rake
  script/policies_for_simulated_renewals.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#3543 78769
  app/views/exchanges/employer_applications/_index.html.erb
  features/employers/benefit_applications/admin_terminating_benefit_application_steps.rb
  features/employers/benefit_applications/terminated/admin_terminating_benefit_application.feature
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Promote to Test Environment, Tracker: Bug

#3518 85092
  app/data_migrations/remove_invalid_address_for_person.rb
  lib/tasks/migrations/remove_invalid_address_for_person.rake
  spec/data_migrations/remove_invalid_address_for_person_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Data

#3535 84322
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Promote to Test Environment, Tracker: Bug

#3550 86552
  app/views/insured/families/_enrollment.html.erb
  app/views/insured/group_selection/edit_plan.html.erb
  app/views/shared/_carrier_contact_information.html.erb
  features/step_definitions/individual_steps.rb
  spec/views/shared/_carrier_contact_information.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3528 82213
  app/models/factories/enrollment_factory.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3552 85750
  app/helpers/broker_agencies/profiles_helper.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/general_agencies/general_agency_profiles/_general_agency_staff_table.html.erb
  spec/helpers/broker_agencies/profiles_helper_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3533 85039
  components/sponsored_benefits/app/models/sponsored_benefits/benefit_applications/benefit_application.rb
  components/sponsored_benefits/app/models/sponsored_benefits/benefit_applications/plan_design_proposal_builder.rb
  components/sponsored_benefits/app/models/sponsored_benefits/forms/plan_design_proposal.rb
  components/sponsored_benefits/app/models/sponsored_benefits/organizations/plan_design_proposal_builder.rb
  components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals/proposal_copies_controller_spec.rb
  components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals_controller_spec.rb
  components/sponsored_benefits/spec/dummy/app/models/benefit_sponsors/organizations/aca_shop_dc_employer_profile.rb
  components/sponsored_benefits/spec/models/sponsored_benefits/benefit_applications/benefit_application_spec.rb
  components/sponsored_benefits/spec/models/sponsored_benefits/organizations/plan_design_organization_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3530 82373
  app/controllers/insured/plan_shoppings_controller.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug
