Repository dchbx/enroll, pull requests merged in 2020-04, with the labels that each got.

#3566 42317
  app/controllers/insured/consumer_roles_controller.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Peer Review, Tracker: Bug

#3564 85769
  script/fix_vlp_document_other_i94.rb
  spec/script/fix_vlp_document_other_i94_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Data

#3561 82303
  app/helpers/broker_agencies/profiles_helper.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_broker_agency_staff_table.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/general_agencies/general_agency_profiles/_general_agency_staff_table.html.erb
  spec/helpers/broker_agencies/profiles_helper_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3568 86922
  app/assets/javascripts/qle.js.erb
  app/controllers/concerns/sep_all.rb
  app/controllers/insured/employee_roles_controller.rb
  app/helpers/insured/families_helper.rb
  app/models/hbx_enrollment.rb
  app/models/qualifying_life_event_kind.rb
  app/models/special_enrollment_period.rb
  app/views/insured/families/_effective_on_kind_fields.html.erb
  app/views/insured/families/_qle_detail.html.erb
  app/views/insured/group_selection/new.html.erb
  features/employee/employee_plan_shopping_with_covid_qle.feature
  features/step_definitions/employee_steps.rb
  spec/models/hbx_enrollment_spec.rb
  spec/models/qualifying_life_event_kind_spec.rb
  spec/models/special_enrollment_period_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Epic (Master Ticket)

#3569 86712
  app/views/insured/families/verification/_verification.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3555 86326
  app/models/hbx_enrollment.rb
  components/benefit_sponsors/spec/dummy/app/models/hbx_enrollment.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3521 86102
  components/benefit_sponsors/app/models/benefit_sponsors/factories/enrollment_renewal_factory.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/factories/enrollment_renewal_factory_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3577 87011
  app/assets/javascripts/qle.js.erb
  app/controllers/concerns/sep_all.rb
  app/helpers/insured/families_helper.rb
  app/models/qualifying_life_event_kind.rb
  app/views/exchanges/hbx_profiles/update_effective_date.js.erb
  app/views/insured/families/_effective_on_kind_fields.html.erb
  features/employee/employee_plan_shopping_with_covid_qle.feature
  features/step_definitions/employee_steps.rb
  spec/controllers/concerns/sep_all_spec.rb
  spec/models/qualifying_life_event_kind_spec.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Enhancement

#3584 42198
  app/data_migrations/destroy_self_relationship_kind.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Bug

#3573 86964
  app/views/employers/employer_profiles/my_account/_employer_welcome.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_employer_welcome.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_old_employer_welcome.html.erb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Hot Fix

#3476 83256
  app/controllers/application_controller.rb
  app/controllers/exchanges/agents_controller.rb
  app/models/invitation.rb
  components/benefit_sponsors/app/controllers/benefit_sponsors/application_controller.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/general_agencies/general_agency_profiles/_show.html.erb
  features/step_definitions/ga_staff_steps.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/broker_agencies/profiles_controller_spec.rb
  spec/controllers/broker_agencies/quotes_controller_spec.rb
  spec/controllers/employers/census_employees_controller_spec.rb
  spec/controllers/employers/employer_profiles_controller_spec.rb
  spec/controllers/employers/inboxes_controller_spec.rb
  spec/controllers/employers/people_controller_spec.rb
  spec/controllers/exchanges/broker_applicants_controller_spec.rb
  spec/controllers/exchanges/hbx_profiles_controller_spec.rb
  spec/controllers/exchanges/inboxes_controller_spec.rb
  spec/controllers/exchanges/scheduled_events_controller_spec.rb
  spec/controllers/insured/consumer_roles_controller/consumer_roles_controller_update_spec.rb
  spec/controllers/insured/employee_roles_controller_spec.rb
  spec/controllers/insured/families_controller_spec.rb
  spec/controllers/insured/family_members_controller/family_members_controller_update_spec.rb
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/controllers/insured/inboxes_controller_spec.rb
  spec/controllers/insured/interactive_identity_verifications_controller_spec.rb
  spec/controllers/invitations_controller_spec.rb
  spec/controllers/saml_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/controllers/welcome_controller_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Hot Fix

#3591 87026
  .github/workflows/ruby.yml
  components/notifier/app/models/notifier/builders/employee_profile.rb
  components/notifier/spec/models/notifier/builders/employee_profile_spec.rb
  test_utilities/report_to_yellr.sh
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3586 87116
  app/data_migrations/invalidate_hbx_enrollment_with_broken_current_premium.rb
  app/helpers/insured/families_helper.rb
  lib/tasks/migrations/invalidate_hbx_enrollment_with_broken_current_premium.rake
  spec/data_migrations/invalidate_hbx_enrollment_with_broken_current_premium_spec.rb
  spec/helpers/insured/families_helper_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3565 63558
  app/data_migrations/remove_all_duplicate_family_members.rb
  lib/tasks/migrations/remove_all_duplicate_family_members.rake
  spec/data_migrations/remove_all_duplicate_family_members_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#3595 70259
  app/models/forms/family_member.rb
  spec/models/forms/family_member_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Peer Review, Tracker: Bug

#3599 87223
  app/models/factories/family_enrollment_clone_factory.rb
  spec/models/factories/family_enrollment_clone_factory_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3596 87179
  app/controllers/products/qhp_controller.rb
  spec/controllers/products/qhp_controller_spec.rb
  spec/notices/ivl_notices/enrollment_notice_builder_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3585 87119
  app/models/census_employee.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3589 86885
  app/models/subscribers/policy_terminations_subscriber.rb
  spec/models/subscribers/policy_terminations_subscriber_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Bug

#3601 38217
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3613 86158
  app/views/user_mailer/broker_invitation_email.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3614 87224
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/factories/profile_factory_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3612 87254
  app/controllers/inboxes_controller.rb
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/hbx_profile.rb
  components/benefit_sponsors/spec/factories/benefit_sponsors_organizations_hbx_profiles.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/hbx_profile_spec.rb
  spec/controllers/broker_agencies/inboxes_controller_spec.rb
  spec/controllers/employers/inboxes_controller_spec.rb
  spec/controllers/insured/inboxes_controller_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3600 81780
  app/views/shared/engines/_broker_menu.html.erb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3427 69937
  lib/tasks/hbx_reports/enrollapp_report.rake
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#3551 86510
  app/data_migrations/remove_dependent.rb
  app/models/family.rb
  app/models/forms/family_member.rb
  app/models/household.rb
  app/models/tax_household.rb
  app/views/insured/families/_family.html.erb
  app/views/insured/family_members/_dependent_resident_form.html.erb
  app/views/insured/family_members/_destroyed.html.erb
  app/views/insured/family_members/destroyed.js.erb
  lib/remove_family_member.rb
  lib/tasks/migrations/remove_dependent.rake
  spec/controllers/insured/family_members_controller_spec.rb
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/data_migrations/remove_dependent_spec.rb
  spec/models/family_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3529 83418
  app/views/insured/plan_shoppings/show.html.slim
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#3520 84730
  app/assets/javascripts/ui-components/forms.js.erb
  app/controllers/broker_agencies/profiles_controller.rb
  app/controllers/general_agencies/profiles_controller.rb
  app/data_migrations/delink_broker_general_agency.rb
  app/helpers/events_helper.rb
  app/javascript/benefit_sponsors/controllers/office_locations_controller.js
  app/models/broker_role.rb
  app/models/person.rb
  app/views/employers/employer_profiles/_employer_broker_widget.html.erb
  app/views/events/v2/phones/_phone.xml.haml
  app/views/ui-components/v1/forms/office_locations/_old_style_address.html.erb
  app/views/ui-components/v1/forms/office_locations/_phone.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/shared/_office_location_fields.html.erb
  components/benefit_sponsors/db/seedfiles/cca/fixtures/issuer_profile_210004.yaml
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/registrations_controller_spec.rb
  components/benefit_sponsors/spec/dummy/app/models/broker_role.rb
  components/benefit_sponsors/spec/dummy/app/models/person.rb
  components/benefit_sponsors/spec/dummy/app/models/phone.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/office_location_form_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/profile_form_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/registration_form_spec.rb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/office_locations/_office_location_fields.html.erb
  components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_organizations_controller_spec.rb
  db/seedfiles/cca/fixtures/issuer_profile_210004.yaml
  features/brokers/broker_registration.feature
  features/step_definitions/cca_sole_source_benefit_package_steps.rb
  features/step_definitions/integration_steps.rb
  features/step_definitions/manage_family.rb
  features/support/worlds/census_employee_world.rb
  lib/tasks/hbx_reports/employer_changes.rake
  lib/tasks/migrations/add_phones_to_people.rake
  spec/controllers/broker_agencies/broker_roles_controller_spec.rb
  spec/controllers/broker_agencies/profiles_controller_spec.rb
  spec/controllers/general_agencies/profiles_controller_spec.rb
  spec/data_migrations/delink_broker_general_agency_spec.rb
  spec/models/broker_role_spec.rb
  spec/models/forms/broker_agency_profile_spec.rb
  spec/models/forms/general_agency_profile_spec.rb
  spec/views/employers/employer_profiles/_employer_broker_widget.html.erb_spec.rb
  spec/views/events/v2/organizations/_office_locations.haml_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3605 42198
  app/data_migrations/destroy_self_relationship_kind.rb
Labels: Priority: 1-Immediate, Status: Peer Review, Tracker: Bug

#3615 28878
  app/models/factories/family_enrollment_clone_factory.rb
  spec/models/factories/family_enrollment_clone_factory_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3602 43093
  app/views/insured/families/_waived_coverage_widget.erb
  components/benefit_markets/db/seedfiles/translations/en/insured.rb
  components/benefit_sponsors/db/seedfiles/translations/en/insured.rb
  db/seedfiles/translations/en/insured.rb
  spec/views/insured/families/_enrollment.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3603 43094
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/employee_waiver_confirmation_spec.rb
  components/notifier/app/models/notifier/builders/enrollment.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3624 87305
  app/views/shared/engines/_broker_menu.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3623 61530
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/submit_application.js.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3554 43055
  app/controllers/employers/census_employees_controller.rb
  app/models/census_employee.rb
  features/employers/cobra_sole_source.feature
  features/step_definitions/employers_steps.rb
  spec/controllers/employers/census_employees_controller_spec.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3625 74909
  app/models/census_employee.rb
  components/benefit_sponsors/spec/dummy/app/models/census_employee.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3618 55329
  components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/_sponsored_benefit.html.slim
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3617 40158
  app/models/concerns/config/contact_center_model_concern.rb
  app/models/person.rb
  components/benefit_sponsors/spec/dummy/app/models/person.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_spec.rb
  spec/models/person_spec.rb
Labels: Mergeable: Yes, Priority: 5-Low, Status: Accepted Pending Release, Tracker: Code Refactor

#3607 30275
  app/views/insured/family_members/index.html.erb
  spec/views/insured/family_members/index.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3608 42289
  app/helpers/insured/families_helper.rb
  app/views/people/landing_pages/_personal.html.erb
  app/views/people/landing_pages/_personal_coverall.html.erb
  spec/helpers/insured/families_helper_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3509 85762
  app/assets/javascripts/demographics_fields.js
  app/controllers/concerns/vlp_doc.rb
  app/controllers/documents_controller.rb
  app/controllers/exchanges/hbx_profiles_controller.rb
  app/controllers/people_controller.rb
  app/data_migrations/delete_uploaded_files.rb
  app/data_migrations/set_active_vlp_document.rb
  app/domain/operations/call_fed_hub.rb
  app/domain/operations/update_dob_ssn.rb
  app/domain/operations/validate_vlp_document.rb
  app/domain/validators/vlp_v37_contract.rb
  app/models/consumer_role.rb
  app/models/vlp_document.rb
  app/views/exchanges/hbx_profiles/_edit_enrollment.html.erb
  app/views/insured/consumer_roles/_i_94_2_fields.html.erb
  app/views/insured/consumer_roles/_i_94_fields.html.erb
  app/views/insured/consumer_roles/_other_with_alien_number_fields.html.erb
  app/views/insured/consumer_roles/_other_with_i94_fields.html.erb
  app/views/insured/consumer_roles/docs_shared/_document_description.html.erb
  app/views/insured/consumer_roles/docs_shared/_expiration_date.html.erb
  db/seedfiles/translations/en/insured.rb
  features/insured/individual_immigration_details.feature
  features/insured/individual_vlp_verification.feature
  features/insured/step_definitions/individual_immigration_details_steps.rb
  features/step_definitions/individual_steps.rb
  lib/tasks/delete_uploaded_files.rake
  lib/tasks/set_active_vlp_document.rake
  script/report_of_people_with_inconsistent_migration.rb
  spec/controllers/concerns/vlp_doc_spec.rb
  spec/controllers/documents_controller_spec.rb
  spec/controllers/exchanges/hbx_profiles_controller_spec.rb
  spec/controllers/people_controller_spec.rb
  spec/data_migrations/delete_uploaded_files_spec.rb
  spec/data_migrations/set_active_vlp_document_spec.rb
  spec/domain/operations/call_fed_hub_spec.rb
  spec/domain/operations/update_dob_ssn_spec.rb
  spec/domain/operations/validate_vlp_document_spec.rb
  spec/domain/validators/vlp_v37_contract_spec.rb
  spec/models/consumer_role_spec.rb
  spec/views/insured/consumer_roles/_form.html.erb_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: App-Dev_Feature

#3501 85911
  app/helpers/application_helper.rb
  app/models/person.rb
  app/views/shared/brokers/_applicants_index.html.erb
  features/brokers/broker_reapplication.feature
  features/step_definitions/brokers_steps.rb
  spec/helpers/application_helper_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Enhancement

#3646 87521
  config/settings.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3636 87459
  app/models/effective/datatables/user_account_datatable.rb
  features/admin/user_account.feature
  features/step_definitions/user_accounts.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#3627 87357
  app/views/shared/engines/_broker_menu.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug
