Repository dchbx/enroll, pull requests merged in 2020-01, with the labels that each got.

#3417 82720
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
  script/transition_ee_to_enrolled.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3380 62023
  app/models/admin/aptc.rb
  spec/models/admin/aptc_spec.rb
Labels: Priority: 2-Urgent, Status: Functional Testing, Tracker: App-Dev_Use Case

#3361 60829
  app/assets/javascripts/aptc.js.erb
  app/controllers/hbx_admin_controller.rb
  app/views/hbx_admin/_edit_aptc_csr_active_enrollment.html.erb
  spec/controllers/hbx_admin_controller_spec.rb
Labels: Priority: 4-Normal, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#3415 81794
  config/settings.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3407 81506
  app/models/hbx_enrollment.rb
  app/models/importers/transcripts/enrollment_actions.rb
  app/models/importers/transcripts/enrollment_transcript.rb
  app/models/parsers/xml/cv/importers/enrollment_parser.rb
  app/models/transcripts/base.rb
  app/models/transcripts/enrollment_common.rb
  app/models/transcripts/enrollment_transcript.rb
  spec/models/importers/transcripts/enrollment_transcript_spec.rb
  spec/models/transcripts/enrollment_transcript_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#3396 80501
  config/settings.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3423 81809
  components/benefit_sponsors/app/data_migrations/update_office_location.rb
  lib/tasks/migrations/components/update_office_location.rake
  spec/data_migrations/update_office_location_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3425 76036
  app/data_migrations/add_coverage_household_member.rb
  app/data_migrations/destroy_self_relationship_kind.rb
  app/data_migrations/update_coverage_household_member.rb
  lib/tasks/migrations/add_coverage_household_member.rake
  lib/tasks/migrations/destroy_self_relationship_kind.rake
  lib/tasks/migrations/update_coverage_household_member.rake
  lib/tasks/migrations/update_person_relationship_kind.rake
  spec/data_migrations/add_coverage_household_member_spec.rb
  spec/data_migrations/destroy_self_relationship_kind_spec.rb
  spec/data_migrations/update_coverage_household_member_spec.rb
  spec/data_migrations/update_person_relationship_kind_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3282 59424
  lib/v2_group_xml_generator.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug
