Repository dchbx/enroll, pull requests merged in 2020-02, with the labels that each got.

#3458 84934
  lib/tasks/migrations/dependent_consumer_role_create.rake
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#3461 84519
  app/assets/javascripts/edit_plan.js
  app/assets/stylesheets/application.scss.erb
  app/models/insured/forms/self_term_or_cancel_form.rb
  app/views/insured/families/_enrollment.html.erb
  app/views/insured/group_selection/_cancel_plan_form.html.erb
  app/views/insured/group_selection/_change_tax_credit_form.html.erb
  app/views/insured/group_selection/edit_plan.html.erb
  app/views/shared/plan_shoppings/_sbc_link.html.erb
Labels: Priority: 4-Normal, Status: Peer Review, Tracker: App-Dev_Use Case

#3466 84876
  components/benefit_markets/app/models/benefit_markets/products/product_package.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3372 64007
  config/settings.yml
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Data

#3472 81807
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/general_agency_profile.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/general_agency_profile_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3465 76701
  app/models/family.rb
  app/models/forms/family_member.rb
  spec/factories/families.rb
  spec/models/forms/family_member_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Data

#3470 83830
  app/views/shared/_contact_preferences.html.erb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3443 71262
  app/models/consumer_role.rb
  app/views/events/lawful_presence/vlp_verification_request.xml.haml
  spec/models/consumer_role_spec.rb
  spec/views/events/lawful_presence/vlp_verification_request.xml.haml_spec.rb
Labels: Assignee: NOT ASSIGNED, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: App-Dev_Feature

#3248 42635
  components/notifier/app/models/notifier/notice_builder.rb
  components/notifier/spec/models/notifier/notice_builder_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: App-Dev_Feature

#3479 85323
  components/benefit_sponsors/app/models/benefit_sponsors/services/new_profile_registration_service.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/new_profile_registration_service_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3469 85321
  components/benefit_sponsors/app/models/benefit_sponsors/services/new_profile_registration_service.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/new_profile_registration_service_spec.rb
  features/employers/employer_profile.feature
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3448 84733
  app/helpers/insured/group_selection_helper.rb
  spec/helpers/insured/group_selection_helper_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3308 43855
  app/models/forms/bulk_actions_for_admin.rb
  app/models/hbx_enrollment.rb
  spec/models/forms/bulk_actions_for_admin_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3492 85743
  app/views/exchanges/hbx_profiles/_new_benefit_application.html.slim
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#3451 84555
  app/controllers/insured/group_selection_controller.rb
  app/models/insured_eligible_for_benefit_rule.rb
  app/views/insured/group_selection/_coverage_household.html.erb
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/models/insured_eligible_for_benefit_rule_spec.rb
  spec/views/insured/group_selection/new.html.erb_spec.rb
Labels: Mergeable: No, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug
