Repository dchbx/enroll, pull requests merged in 2020-09, with the labels that each got.

#3868 89224
  app/assets/stylesheets/custom.scss.erb
  app/views/shared/_address_fields_for_dependent.html.erb
  components/financial_assistance/app/views/financial_assistance/shared/support_text.yml
  features/financial_assistance/health_coverage.feature
  features/financial_assistance/step_definitions/health_coverage_steps.rb
Labels: Assignee: Utkarsh Shukla, Priority: 2-Urgent, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#3855 88885
  app/domain/operations/age_off_relaxed_eligibility.rb
  app/models/enrollments/individual_market/family_enrollment_renewal.rb
  app/models/hbx_enrollment.rb
  app/models/insured_eligible_for_benefit_rule.rb
  spec/domain/operations/shop/age_off_relaxed_eligibility_spec.rb
  spec/models/enrollments/individual_market/family_enrollment_renewal_spec.rb
  spec/models/insured_eligible_for_benefit_rule_spec.rb
  system/config/templates/features/enroll_app/enroll_app.yml
Labels: Priority: 4-Normal, Status: Promote to Test Environment, Tracker: App-Dev_User Story

#3875 89491
  app/models/group_selection_prevarication_adapter.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_staff_roles_controller_spec.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/general_agencies/general_agency_staff_roles_controller_spec.rb
  spec/models/group_selection_prevarication_adapter_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3873 89446
  app/controllers/insured/plan_shoppings_controller.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3849 89153
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship.rb
  components/benefit_sponsors/app/models/benefit_sponsors/queries/broker_families_query.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3874 89299
  app/assets/stylesheets/insured.scss.erb
  components/financial_assistance/app/assets/javascripts/financial_assistance/glossary.js
  components/financial_assistance/app/controllers/financial_assistance/applications_controller.rb
Labels: Priority: 3-High, Status: Promote to Test Environment, Tracker: App-Dev_Use Case

#3900 89523
  lib/tasks/creating_new_enrollment_with_reference_enrollment.rake
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Data

#3909 89590
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Assignee: Alex Thomas, Mergeable: Yes, Priority: 1-Immediate, Status: Functional Testing, Tracker: Support

#3906 89535
  script/projected_eligibility_notice_1.rb
  script/projected_eligibility_notice_2.rb
  spec/components/notifier/builders/consumer_role_spec.rb
  spec/components/notifier/builders/dependent_service_spec.rb
  spec/test_data/notices/proj_elig_report_aqhp_test_data.csv
  spec/test_data/notices/proj_elig_report_uqhp_test_data.csv
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#3911 89633
  config/settings.yml
  spec/models/benefit_coverage_period_spec.rb
  spec/models/enrollment_period/special_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#3914 89693
  app/assets/javascripts/qle.js.erb
  app/domain/validators/qualifying_life_event_kind/qlek_contract.rb
  app/models/special_enrollment_period.rb
  app/views/exchanges/hbx_profiles/update_effective_date.js.erb
  spec/models/special_enrollment_period_spec.rb
Labels: Assignee: Isabella Leung, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: App-Dev_User Story

#3759 89020
  app/assets/javascripts/payment_redirection/kp_payment_redirection.js
  app/controllers/insured/plan_shoppings_controller.rb
  app/controllers/payment_transactions_controller.rb
  app/data_migrations/define_permissions.rb
  app/helpers/insured/plan_shopping/receipt_helper.rb
  app/models/hbx_enrollment.rb
  app/models/one_login/ruby_saml/saml_generator.rb
  app/models/payment_transaction.rb
  app/models/saml_information.rb
  app/models/xml_security/document.rb
  app/views/insured/plan_shoppings/receipt.en.html.erb
  app/views/shared/_shop_for_plans_progress.html.haml
  components/benefit_markets/spec/models/benefit_markets/locations/rating_area_spec.rb
  components/benefit_sponsors/spec/factories/benefit_sponsors_organizations_issuer_profiles.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_sponsorships/aca_shop_benefit_sponsorship_service_spec.rb
  config/saml.yml
  features/insured/individual_pay_now.feature
  features/permissions/pay_now.feature
  features/step_definitions/integration_steps.rb
  features/step_definitions/pay_now_steps.rb
  spec/controllers/payment_transactions_controller_spec.rb
  spec/factories/benefit_packages.rb
  spec/helpers/insured/plan_shopping/receipt_helper_spec.rb
  spec/models/hbx_enrollment_spec.rb
  spec/models/one_login/ruby_saml/saml_generator_spec.rb
  spec/models/payment_transaction_spec.rb
  system/config/templates/features/enroll_app/enroll_app.yml
Labels: Priority: 4-Normal, Status: In Progress, Tracker: App-Dev_Feature

#3920 89770
  app/assets/stylesheets/custom.scss.erb
  app/helpers/application_helper.rb
  app/helpers/config/aca_helper.rb
  app/views/insured/families/find_sep.html.erb
  db/seedfiles/translations/en/dc/insured.rb
  spec/helpers/application_helper_spec.rb
  system/config/templates/features/enroll_app/enroll_app.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Code Refactor

#3934 89853
  app/models/special_enrollment_period.rb
  spec/controllers/insured/family_members_controller_spec.rb
  spec/models/special_enrollment_period_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Hot Fix

#3935 89624
  app/assets/javascripts/application.js.erb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3910 89672
  config/settings.yml
  system/config/templates/features/aca_shop_market/contributions.yml
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support
