Repository dchbx/enroll, pull requests merged in 2020-11, with the labels that each got.

#3996 90508
  app/controllers/concerns/sep_all.rb
  spec/controllers/concerns/sep_all_spec.rb
Labels: Mergeable: No, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#4007 90717
  script/apply_aptc_on_enrollments.rb
Labels: Assignee: Kathlin Nicol, Priority: 4-Normal, Status: Stakeholder Review, Tracker: App-Dev_User Story

#3998 90028
  app/models/services/ivl_enrollment_service.rb
  spec/models/services/ivl_enrollment_service_spec.rb
Labels: Priority: 4-Normal, Status: Functional Testing, Tracker: App-Dev_User Story

#4021 90836
  app/data_migrations/create_renewal_plan_year_and_enrollment.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#4023 90828
  app/data_migrations/create_renewal_plan_year_and_enrollment.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_packages/benefit_package_spec.rb
  lib/tasks/migrations/create_renewal_plan_year_and_enrollment.rake
  spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#4010 90700
  app/assets/javascripts/demographics_fields.js
  app/models/forms/consumer_fields.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#4033 90829
  app/data_migrations/create_renewal_plan_year_and_enrollment.rb
  spec/data_migrations/create_renewal_plan_year_and_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Data

#4025 90849
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Assignee: Kyle Esdaille, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Hot Fix

#4038 90926
  components/notifier/app/helpers/notifier/consumer_role_helper.rb
  components/notifier/app/models/notifier/builders/consumer_role.rb
Labels: Assignee: GoutamReddy Singireddy, Priority: 2-Urgent, Status: Functional Testing, Tracker: App-Dev_Feature

#4035 88751
  app/controllers/products/qhp_controller.rb
  app/views/insured/plan_shoppings/_plan_details.html.erb
  app/views/products/qhp/summary.html.erb
  features/insured/individual_signup.feature
  spec/controllers/products/qhp_controller_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4036 90838
  app/helpers/config/aca_helper.rb
  components/sponsored_benefits/spec/controllers/sponsored_benefits/organizations/plan_design_proposals/benefit_groups_controller_spec.rb
  components/sponsored_benefits/spec/dummy/app/helpers/config/aca_helper.rb
  features/brokers/broker_quote.feature
  spec/models/benefit_group_spec.rb
  system/config/templates/features/aca_shop_market/contributions.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3742 88247
  app/controllers/concerns/error_bubble.rb
  app/controllers/concerns/vlp_doc.rb
  app/controllers/people_controller.rb
  app/models/consumer_role.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/general_agencies/general_agency_staff_roles_controller_spec.rb
  spec/controllers/concerns/vlp_doc_spec.rb
  spec/controllers/insured/family_members_controller/family_members_controller_update_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#4043 90961
  app/models/household.rb
  app/models/subscribers/family_application_completed.rb
  spec/models/subscribers/family_application_completed_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#4009 90135
  app/views/insured/family_members/_dependent_form.html.erb
  app/views/insured/family_members/_dependent_resident_form.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4001 90183
  app/assets/javascripts/group_selection.js
  app/views/insured/group_selection/_coverage_household.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3542 37905
  script/ivl_renewal_notices.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Enhancement

#4004 89903
  app/models/general_agency_staff_role.rb
  components/benefit_sponsors/app/models/benefit_sponsors/services/staff_role_service.rb
  features/financial_assistance/job_income.feature
  features/general_agencies/step_definitions/ga_steps.rb
  features/general_agencies/update_general_agency_profile.feature
  features/general_agencies/update_general_agency_profile.feature.wip
  features/insured/individual_sep_signup.feature
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4016 90518
  app/controllers/application_controller.rb
  app/models/coverage_household.rb
  app/views/insured/group_selection/_coverage_household.html.erb
  spec/models/coverage_household_spec.rb
  spec/views/insured/group_selection/new.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#4027 89530
  app/models/hbx_enrollment.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Assignee: Ken Hill, Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#4046 90955
  lib/tasks/employers_failing_minimum_participation.rake
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Data

#4011 90628
  app/models/forms/family_member.rb
  spec/models/forms/family_member_spec.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug
