Repository dchbx/enroll, pull requests merged in 2020-06, with the labels that each got.

#3683 87928
  app/models/enrollment_shopping/affected_enrollment_finder.rb
  app/models/hbx_enrollment.rb
  spec/data_migrations/change_enrollment_details_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Hot Fix

#3651 42267
  app/models/family.rb
  components/benefit_sponsors/spec/dummy/app/models/family.rb
  spec/models/family_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3635 87904
  Gemfile
  Gemfile.lock
  components/benefit_markets/Gemfile.lock
  components/benefit_sponsors/Gemfile.lock
  components/benefit_sponsors/yarn.lock
  components/notifier/Gemfile.lock
  components/notifier/app/models/notifier/notice_kind.rb
  components/notifier/notifier.gemspec
  components/sponsored_benefits/Gemfile.lock
  components/transport_gateway/Gemfile.lock
  components/transport_profiles/Gemfile.lock
  components/transport_profiles/transport_profiles.gemspec
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3628 40159
  app/controllers/insured/plan_shoppings_controller.rb
  app/views/user_mailer/secure_purchase_confirmation.html.erb
  features/employee/employee_plan_shopping.feature
  features/step_definitions/integration_steps.rb
  spec/controllers/insured/plan_shoppings_controller_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#3660 87139
  app/models/document.rb
  config/settings.yml
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Data

#3682 87852
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
Labels: Assignee: Alex Thomas, Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3665 87505
  Gemfile.lock
  app/helpers/config/aca_helper.rb
  app/helpers/config/site_helper.rb
  app/models/consumer_role.rb
  app/models/subscribers/local_residency.rb
  app/models/verification_type.rb
  components/benefit_sponsors/spec/dummy/app/helpers/config/site_helper.rb
  config/initializers/resource_registry.rb
  spec/models/consumer_role_spec.rb
  spec/models/lawful_presence_determination_spec.rb
  spec/models/subscribers/local_residency_spec.rb
  spec/models/verification_type_spec.rb
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
  system/config/templates/features/enroll_app/enroll_app.yml
Labels: Assignee: Kathlin Nicol, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Epic (Master Ticket)

#3689 85736
  app/views/events/v2/employers/_broker_agency_account.xml.haml
  spec/views/events/v2/employers/_broker_agency_account.xml.haml_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Bug

#3685 87770
  app/models/hbx_enrollment.rb
  components/benefit_sponsors/spec/dummy/app/models/hbx_enrollment.rb
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3692 87800
  app/models/queries/user_datatable_query.rb
  app/models/user.rb
  features/support/worlds/permissions_world.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#3695 88055
  app/models/hbx_enrollment.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3691 87896
  app/models/factories/enrollment_factory.rb
  spec/models/factories/enrollment_factory_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3701 87971
  app/models/admin/aptc.rb
  spec/controllers/hbx_admin_controller_spec.rb
  spec/models/admin/aptc_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3696 87989
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles_controller.rb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/broker_agencies/broker_agency_profiles/_staff_table.html.erb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3598 82267
  app/helpers/insured/families_helper.rb
  app/models/family.rb
  app/models/hbx_enrollment.rb
  app/views/insured/families/_enrollment.html.erb
  features/employee/employee_plan_shopping_make_changes_button_display.feature
  features/step_definitions/employers_steps.rb
  features/step_definitions/integration_steps.rb
  features/step_definitions/new_hire_steps.rb
  features/support/worlds/census_employee_world.rb
  spec/helpers/insured/families_helper_spec.rb
  spec/models/hbx_enrollment_spec.rb
  spec/views/employers/census_employees/show.html.erb_spec.rb
  spec/views/insured/families/_enrollment.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3515 66905
  app/models/census_employee.rb
  app/models/hbx_enrollment.rb
  app/views/insured/families/_shop_for_plans_widget.html.erb
  spec/models/census_employee_spec.rb
  spec/models/forms/consumer_candidate_spec.rb
  spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3620 87330
  app/views/events/shared/_affected_member.xml.haml
  app/views/events/shared/_enrollee.xml.haml
  spec/data_migrations/change_state_for_passive_enrollment_spec.rb
  spec/models/forms/consumer_candidate_spec.rb
  spec/models/lawful_presence_determination_spec.rb
  spec/notices/shop_employer_notices/initial_employer_ineligibility_notice_spec.rb
  spec/views/events/hbx_enrollment/enrollment_event.xml.haml_spec.rb
  spec/views/events/lawful_presence/vlp_verification_request.xml.haml_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#3680 87679
  app/controllers/insured/plan_shoppings_controller.rb
  app/data_migrations/fix_2020_ivl_benefit_packages.rb
  app/data_migrations/fix_csr_eligibility_kinds_for_eds_with_csr_percent_zero.rb
  app/helpers/application_helper.rb
  app/models/benefit_coverage_period.rb
  app/models/eligibility_determination.rb
  app/models/enrollments/individual_market/open_enrollment_begin.rb
  app/models/factories/eligibility_factory.rb
  app/models/family.rb
  app/models/household.rb
  app/models/plan.rb
  app/models/services/checkbook_services/plan_comparision.rb
  app/models/tax_household.rb
  app/reports/hbx_reports/report_for_bad_eligibile_families.rb
  app/views/exchanges/hbx_profiles/_new_eligibility.html.erb
  app/views/hbx_admin/_demographics_info.html.erb
  app/views/hbx_admin/_household_header.html.erb
  app/views/insured/plan_shoppings/_plan_details.html.erb
  components/benefit_markets/app/models/benefit_markets/products/product.rb
  components/benefit_markets/spec/dummy/app/models/eligibility_determination.rb
  components/benefit_sponsors/spec/dummy/app/models/eligibility_determination.rb
  components/sponsored_benefits/spec/dummy/app/models/eligibility_determination.rb
  components/sponsored_benefits/spec/dummy/app/models/plan.rb
  features/insured/plan_shopping_with_mixed_household_determination.feature
  features/step_definitions/individual_steps.rb
  features/step_definitions/plan_shopping_with_mixed_household_determination_steps.rb
  features/support/worlds/ivl_assistance_world.rb
  lib/tasks/fix_2020_ivl_benefit_packages.rake
  lib/tasks/fix_csr_eligibility_kinds_for_eds_with_csr_percent_zero.rake
  lib/tasks/migrations/create_2020_ivl_pacakges.rake
  script/report_of_ivl_people_with_csr_percent_100.rb
  spec/data_migrations/fix_2020_ivl_benefit_packages_spec.rb
  spec/data_migrations/fix_csr_eligibility_kinds_for_eds_with_csr_percent_zero_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/models/eligibility_determination_spec.rb
  spec/models/factories/eligibility_factory_spec.rb
  spec/models/factories/ivl_plan_shopping_eligibility_factory_spec.rb
  spec/models/household_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3697 54246
  app/models/family.rb
  app/models/hbx_enrollment.rb
  features/support/worlds/census_employee_world.rb
  spec/controllers/insured/families_controller_spec.rb
  spec/models/family_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Returned for Deficiency, Tracker: Bug

#3706 88138
  app/views/employers/census_employees/show.html.erb
  app/views/shared/_past_enrollments.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support
