Repository dchbx/enroll, pull requests merged in 2020-10, with the labels that each got.

#3932 89704
  app/models/census_employee.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/spec/dummy/app/models/benefit_group_assignment.rb
  components/benefit_sponsors/spec/dummy/app/models/census_employee.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3944 89887
  lib/tasks/hbx_reports/newly_registered_persons_data_report.rake
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Data

#3912 89476
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3755 88640
  script/ivl_sep_query.rb
Labels: Assignee: Alix Pereira, Priority: 4-Normal, Status: Stakeholder Review, Tracker: App-Dev_User Story

#3962 90244
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3963 90280
  app/models/tax_household.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Hot Fix

#3961 90133
  app/assets/javascripts/application.js.erb
  app/assets/javascripts/employee_dependent.js
  app/controllers/concerns/error_bubble.rb
  app/controllers/exchanges/residents_controller.rb
  app/controllers/insured/family_members_controller.rb
  app/domain/validators/address_contract.rb
  app/views/insured/family_members/_dependent_form.html.erb
  app/views/insured/family_members/_dependent_resident_form.html.erb
  app/views/insured/family_members/edit.js.erb
  app/views/insured/family_members/edit_resident_dependent.js.erb
  app/views/insured/family_members/new.js.erb
  app/views/insured/family_members/new_resident_dependent.js.erb
  app/views/shared/_address_error_messages.html.erb
  app/views/shared/_address_fields_for_dependent.html.erb
  app/views/shared/_consumer_home_address_fields.html.erb
  app/views/shared/_resident_home_address_fields.html.erb
  features/financial_assistance/family_relationships_page.feature
  features/hbx_admin/step_definitions/manage_sep_types_steps.rb
  spec/controllers/insured/consumer_roles_controller_spec.rb
  spec/controllers/insured/family_members_controller/family_members_controller_update_spec.rb
  spec/controllers/insured/family_members_controller_spec.rb
  spec/controllers/insured/resident_roles_controller_spec.rb
  spec/domain/validators/address_contract_spec.rb
Labels: Mergeable: No, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Code Refactor

#3946 90020
  app/models/services/ivl_enrollment_service.rb
  spec/models/services/ivl_enrollment_service_spec.rb
Labels: Assignee: Alix Pereira, Priority: 2-Urgent, Status: Stakeholder Review, Tracker: App-Dev_Use Case

#3957 90115
  app/helpers/insured/plan_shopping/receipt_helper.rb
  spec/helpers/insured/plan_shopping/receipt_helper_spec.rb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: App-Dev_Feature

#3988 90451
  components/benefit_markets/app/domain/benefit_markets/operations/benefit_markets/create_benefit_sponsor_catalog.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Data

#3973 89876
  app/models/user.rb
  app/views/shared/_my_portal_links.html.erb
  spec/models/user_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3972 88778
  app/views/employers/employer_profiles/my_account/_home_tab.html.slim
  app/views/ui-components/v1/cards/_benefit_groups.html.slim
  spec/views/employers/employer_profiles/my_account/home_tab.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3987 90424
  config/settings.yml
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#3964 89875
  app/controllers/insured/group_selection_controller.rb
  features/employers/benefit_applications/draft/admin_draft_enrollment_extension.feature
  spec/controllers/insured/group_selection_controller_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3994 90245
  app/views/insured/families/_personal.html.erb
  app/views/insured/families/personal.js.erb
  app/views/insured/family_members/edit.js.erb
  app/views/people/landing_pages/_personal.html.erb
  app/views/shared/_consumer_home_address_fields.html.erb
  app/views/shared/_home_address_fields.html.erb
  components/financial_assistance/app/views/financial_assistance/applicants/_edit.html.erb
  components/financial_assistance/app/views/financial_assistance/shared/_consumer_home_address_fields.html.erb
  features/insured/individual_signup.feature
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#3986 90396
  app/assets/javascripts/date.js
  app/views/insured/employee_roles/search.html.slim
  app/views/insured/family_members/_dependent_form.html.erb
  app/views/insured/family_members/_dependent_resident_form.html.erb
Labels: Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#3942 88771
  app/views/insured/plan_shoppings/_plan_details.html.erb
  features/insured/individual_assisted_signup.feature
  features/step_definitions/individual_steps.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3985 89585
  app/controllers/concerns/sep_all.rb
  app/controllers/exchanges/manage_sep_types_controller.rb
  app/controllers/insured/families_controller.rb
  app/domain/entities/qualifying_life_event_kind.rb
  app/domain/operations/qualifying_life_event_kind/sort.rb
  app/domain/operations/qualifying_life_event_kind/transform.rb
  app/domain/validators/qualifying_life_event_kind/qlek_contract.rb
  app/models/effective/datatables/sep_type_data_table.rb
  app/models/forms/qualifying_life_event_kind_form.rb
  app/models/insured_eligible_for_benefit_rule.rb
  app/models/qualifying_life_event_kind.rb
  app/models/special_enrollment_period.rb
  app/views/exchanges/hbx_profiles/update_effective_date.js.erb
  app/views/exchanges/manage_sep_types/_expire.html.erb
  app/views/exchanges/manage_sep_types/edit.html.erb
  app/views/exchanges/manage_sep_types/new.html.erb
  app/views/exchanges/manage_sep_types/sep_type_datatable.html.erb
  components/benefit_sponsors/spec/dummy/app/models/qualifying_life_event_kind.rb
  components/benefit_sponsors/spec/dummy/app/models/special_enrollment_period.rb
  components/financial_assistance/spec/dummy/app/models/qualifying_life_event_kind.rb
  db/seedfiles/ivl_life_events_seed.rb
  db/seedfiles/qualifying_life_event_kinds_seed.rb
  db/seedfiles/translations/en/dc/manage_sep_types.rb
  script/update_qle_effective_on_kinds.rb
  spec/controllers/concerns/sep_all_spec.rb
  spec/controllers/exchanges/manage_sep_types_controller_spec.rb
  spec/controllers/insured/families_controller_spec.rb
  spec/domain/entities/qualifying_life_event_kind_spec.rb
  spec/domain/operations/qualifying_life_event_kind/persist_spec.rb
  spec/domain/operations/qualifying_life_event_kind/sort_spec.rb
  spec/domain/operations/qualifying_life_event_kind/transform_spec.rb
  spec/domain/validators/qualifying_life_event_kind/qlek_contract_spec.rb
  spec/helpers/insured/families_helper_spec.rb
  spec/models/effective/datatable/sep_type_data_table_spec.rb
  spec/models/enrollment_period/special_enrollment_spec.rb
  spec/models/qualifying_life_event_kind_spec.rb
  spec/models/special_enrollment_period_spec.rb
  system/config/templates/features/enroll_app/sep_types.yml
Labels: Assignee: Sarah Bagge, Priority: 4-Normal, Status: Stakeholder Review, Tracker: Epic (Master Ticket)

#3983 90088
  app/helpers/time_helper.rb
  app/models/forms/family_member.rb
  spec/models/forms/family_member_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3975 90238
  components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/contribution_level.rb
  components/benefit_sponsors/app/models/benefit_sponsors/sponsored_benefits/sponsor_contribution.rb
  components/benefit_sponsors/spec/dummy/system/config/templates/features/aca_shop_market/contributions.yml
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/sponsored_benefits/contribution_level_spec.rb
  system/config/templates/features/aca_shop_market/contributions.yml
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: App-Dev_User Story
