Repository dchbx/enroll, pull requests merged in 2020-12, with the labels that each got.

#4047 91042
  app/models/time_keeper.rb
  components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3732 88264
  app/data_migrations/create_renewal_plan_year_and_enrollment.rb
  app/models/hbx_enrollment.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#4044 89516
  app/helpers/portal_header_helper.rb
  spec/helpers/portal_header_helper_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4052 90699
  app/models/employee_role.rb
  components/benefit_sponsors/app/controllers/benefit_sponsors/profiles/employers/employer_profiles_controller.rb
  spec/models/employee_role_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#4049 90668
  app/views/insured/plan_shoppings/show.html.slim
  features/group_selection/ivl_plan_shopping.feature
  features/step_definitions/group_selection_steps.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#4051 91005
  app/controllers/people_controller.rb
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#4060 91069
  app/views/insured/families/_shop_for_plans_widget.html.erb
  spec/views/insured/families/_shop_for_plans_widget.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#4069 91081
  app/helpers/insured/families_helper.rb
  app/models/hbx_enrollment.rb
  app/views/insured/families/_enrollment.html.erb
  features/step_definitions/employee_steps.rb
  spec/helpers/insured/families_helper_spec.rb
  spec/models/hbx_enrollment_spec.rb
  spec/views/employers/census_employees/show.html.erb_spec.rb
  spec/views/insured/families/_enrollment.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Data

#4056 90624
  app/policies/employer_profile_policy.rb
  app/views/shared/_signup_progress.html.haml
  spec/factories/permission.rb
  spec/policies/employer_profile_policy_spec.rb
  spec/views/insured/employee_roles/match.html.haml_spec.rb
  spec/views/insured/employee_roles/no_match.html.haml_spec.rb
  spec/views/insured/employee_roles/search.html.haml_spec.rb
  spec/views/insured/family_members/index.html.erb_spec.rb
  spec/views/insured/group_selection/new.html.erb_spec.rb
  spec/views/insured/plan_shoppings/print_waiver.html.erb_spec.rb
  spec/views/insured/plan_shoppings/receipt.html.erb_spec.rb
  spec/views/insured/plan_shoppings/thankyou.html.erb_spec.rb
  spec/views/shared/_signup_progress.html.haml_spec.rb
  spec/views/shared/signup_progress.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#4074 90943
  app/models/services/ivl_enrollment_service.rb
  spec/models/services/ivl_enrollment_service_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#4071 91273
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_service.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#4090 91792
  features/financial_assistance/step_definitions/fa_not_applying.rb
  features/financial_assistance/step_definitions/financial_assistance_steps.rb
  features/financial_assistance/step_definitions/submit_your_application_steps.rb
  features/financial_assistance/step_definitions/tax_info_steps.rb
  features/step_definitions/household_info_continue_button_steps.rb
  features/support/worlds/financial_assistance/financial_assistance_world.rb
  spec/domain/operations/financial_assistance/apply_spec.rb
  spec/factories/benefit_coverage_periods.rb
  spec/models/family_spec.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Support

#4041 89267
  app/controllers/exchanges/residents_controller.rb
  app/models/forms/family_member.rb
  spec/models/forms/family_member_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4082 91707
  Gemfile
  Gemfile.lock
  config/settings.yml
  spec/models/benefit_coverage_period_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#4028 90742
  app/controllers/exchanges/employer_applications_controller.rb
  app/helpers/employers/employer_helper.rb
  app/views/exchanges/employer_applications/_index.html.erb
  app/views/exchanges/employer_applications/_reinstate_benefit_application_modal.html.erb
  app/views/exchanges/employer_applications/index.js.erb
  db/seedfiles/translations/en/dc/exchange.rb
  features/employers/benefit_applications/admin_reinstate_benefit_application_steps.rb
  features/employers/benefit_applications/admin_terminating_benefit_application_steps.rb
  features/employers/benefit_applications/reinstate/admin_enable_reinstate_benefit_application_permission.feature
  features/employers/benefit_applications/reinstate/admin_reinstate_benefit_application.feature
  features/support/worlds/benefit_market_world.rb
  features/support/worlds/user_world.rb
  spec/controllers/exchanges/employer_applications_controller_spec.rb
  spec/helpers/employers/employer_helper_spec.rb
  spec/views/exchanges/employer_applications/_index.html.erb_spec.rb
  system/config/templates/features/aca_shop_market/aca_shop_market.yml
Labels: Priority: 4-Normal, Status: Peer Review, Tracker: App-Dev_Use Case

#4073 91800
  components/benefit_sponsors/app/models/benefit_sponsors/observers/notice_observer.rb
Labels: Priority: 2-Urgent, Status: Assigned, Tracker: App-Dev_Use Case

#4066 90533
  db/seedfiles/translations/en/dc/insured.rb
  features/step_definitions/group_selection_steps.rb
  spec/views/insured/group_selection/new.html.erb_spec.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#4085 91750
  components/benefit_sponsors/app/domain/benefit_sponsors/entities/benefit_sponsorship.rb
  components/benefit_sponsors/app/domain/benefit_sponsors/validators/benefit_sponsorships/benefit_sponsorship_contract.rb
  components/benefit_sponsors/spec/domain/benefit_sponsors/entities/benefit_sponsorship_spec.rb
  components/benefit_sponsors/spec/domain/benefit_sponsors/validators/benefit_sponsorships/benefit_sponsorship_contract_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4120 91708
  config/settings.yml
  spec/models/benefit_coverage_period_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#4147 92046
  app/controllers/documents_controller.rb
  app/models/document.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#4098 91585
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#4131 91995
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#4089 89862
  app/models/admin/aptc.rb
  app/models/factories/eligibility_factory.rb
  components/benefit_markets/app/models/benefit_markets/products/product.rb
  config/settings.yml
  features/admin/edit_aptc_csr.feature
  features/step_definitions/edit_aptc_csr_steps.rb
  features/support/worlds/ivl_assistance_world.rb
  features/support/worlds/plan_world.rb
  spec/models/factories/eligibility_factory_spec.rb
  spec/models/insured/factories/self_service_factory_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#4064 90514
  app/models/forms/qualifying_life_event_kind_form.rb
  app/views/exchanges/manage_sep_types/new.html.erb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#4154 92081
  app/models/benefit_group_assignment.rb
  app/models/census_employee.rb
  app/models/hbx_enrollment.rb
  app/models/services/ivl_enrollment_service.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_packages/benefit_package.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_sponsorships/benefit_sponsorship_director.rb
  components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug
