Repository dchbx/enroll, pull requests merged in 2020-08, with the labels that each got.

#3667 24535
  app/models/effective/datatables/outstanding_verification_data_table.rb
  app/models/family.rb
  app/views/datatables/shared/_date_filter.html.erb
  spec/models/family_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Peer Review, Tracker: Bug

#3766 88933
  components/benefit_sponsors/app/domain/benefit_sponsors/entities/benefit_application.rb
  components/benefit_sponsors/app/domain/benefit_sponsors/operations/enrollment_eligibility/determine.rb
  components/benefit_sponsors/spec/domain/benefit_sponsors/operations/enrollment_eligibility/determine_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Data

#3760 88851
  app/policies/census_employee_policy.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#3767 88965
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3777 88895
  app/models/hbx_enrollment.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3801 89110
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3754 88192
  app/models/census_employee.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/spec/dummy/app/models/census_employee.rb
  components/benefit_sponsors/spec/dummy/system/config/templates/features/aca_shop_market/aca_shop_market.yml
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  spec/models/census_employee_spec.rb
  system/config/templates/features/aca_shop_market/aca_shop_market.yml
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Code Refactor

#3827 88780
  app/data_migrations/update_product_packages_on_benefit_sponsor_catalogs.rb
  lib/tasks/migrations/update_product_packages_on_benefit_sponsor_catalogs.rake
  spec/data_migrations/update_product_packages_on_benefit_sponsor_catalogs_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Data

#3848 89311
  script/ea_uqhp_data_export_ivl_pre.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Data

#3823 89196
  components/notifier/app/models/notifier/notice_builder.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug
