Repository dchbx/enroll, pull requests merged in 2020-05, with the labels that each got.

#3639 87332
  script/destroy_primary_to_primary_relationships.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Data

#3648 87534
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/factories/profile_factory_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3645 87468
  app/views/ui-components/v1/filters/_plan_filters.html.slim
  features/cover_all/consumer_requests_enrollment.feature
  features/step_definitions/integration_steps.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Hot Fix

#3641 87487
  app/views/insured/families/coverall/_missing_paper_application.html.erb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3280 53072
  lib/tasks/hbx_reports/weekly_dependent_relationship_change_report.rake
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#3611 43322
  app/assets/javascripts/application.js.erb
  app/views/insured/family_members/_dependent_form.html.erb
  app/views/people/landing_pages/_personal.html.erb
  app/views/shared/person/_consumer_information.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3619 24535
  app/views/datatables/shared/_date_filter.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3622 43756
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/observers/organization_observer_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#3638 29658
  app/views/notices/ivl/enrollment_notice.html.erb
Labels: Mergeable: Yes, Priority: 5-Low, Status: Promote to Test Environment, Tracker: Bug

#3647 63737
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application_schedular.rb
  components/benefit_sponsors/app/models/benefit_sponsors/importers/mhc/conversion_employer_plan_year_create.rb
  components/benefit_sponsors/app/models/benefit_sponsors/model_events/benefit_application.rb
  components/benefit_sponsors/app/models/benefit_sponsors/scheduled_events/aca_shop_scheduled_events.rb
  components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_service.rb
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_schedular_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/employer_invoice_available_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/generate_initial_invoice_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/initial_employer_invoice_available_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/model_events/initial_employer_no_binder_payment_received_spec.rb
  components/notifier/app/models/notifier/builders/benefit_application.rb
  components/notifier/app/models/notifier/builders/employer_profile.rb
  features/employers/edit_plan_year_for_employer.feature
  features/employers/edit_plan_year_for_renewing_employer.feature
  features/step_definitions/employers_steps.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3637 52266
  app/models/factories/family_enrollment_clone_factory.rb
  features/support/worlds/census_employee_world.rb
  spec/models/factories/family_enrollment_clone_factory_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3563 84457
  app/controllers/insured/group_selection_controller.rb
  app/helpers/insured/group_selection_helper.rb
  spec/helpers/insured/group_selection_helper_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3657 86885
  app/models/subscribers/policy_terminations_subscriber.rb
  spec/models/subscribers/policy_terminations_subscriber_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Bug

#3640 40456
  app/notices/ivl_notices/enrollment_notice_builder.rb
  spec/notices/ivl_notices/enrollment_notice_builder_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3631 43839
  app/mailers/user_mailer.rb
  app/views/user_mailer/new_client_notification.html.erb
  spec/mailers/user_mailer_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Code Refactor

#3560 85566
  script/daily_eligibility_determination_change_report.rb
  spec/script/daily_eligibility_determination_change_report_spec.rb
  spec/script/projected_eligibility_notice_2_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: App-Dev_Use Case

#3239 49374
  components/transport_profiles/app/models/transport_profiles/processes/push_report_eligibility_updated_h41.rb
  components/transport_profiles/db/seedfiles/well_known_endpoint_seed.rb
  components/transport_profiles/spec/models/transport_profiles/processes/push_report_eligiblity_updated_h41s_spec.rb
Labels: Assignee: NOT ASSIGNED, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: App-Dev_Feature

#3653 87299
  app/data_migrations/fix_ed_source_curam_cases.rb
  app/data_migrations/fix_ed_source_non_curam_cases.rb
  app/models/eligibility_determination.rb
  app/models/household.rb
  features/step_definitions/individual_steps.rb
  features/support/worlds/ivl_assistance_world.rb
  lib/tasks/create_tax_household.rake
  script/daily_eligibility_determination_change_report.rb
  script/update_eligibility.rb
  spec/controllers/hbx_admin_controller_spec.rb
  spec/data_migrations/fix_ed_source_curam_cases_spec.rb
  spec/data_migrations/fix_ed_source_non_curam_cases_sepc.rb
  spec/data_migrations/reactivate_tax_household_with_assistance_year_spec.rb
  spec/factories/eligibility_determinations.rb
  spec/models/eligibility_determination_spec.rb
  spec/models/household_spec.rb
  spec/script/daily_eligibility_determination_change_report_spec.rb
  spec/script/projected_eligibility_notice_2_spec.rb
  spec/support/bradys_after_all.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#3662 87681
  app/views/insured/employee_roles/_employment_relationships.html.haml
  app/views/insured/employee_roles/match.html.haml
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3634 87036
  app/controllers/insured/group_selection_controller.rb
  features/employee/employee_passive_renewal_update.feature
  spec/controllers/insured/group_selection_controller_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3338 68577
  app/helpers/insured/families_helper.rb
  app/models/group_selection_prevarication_adapter.rb
  app/views/insured/families/_shop_for_plans_widget.html.erb
  features/step_definitions/group_selection_steps.rb
  spec/controllers/insured/group_selection_controller_spec.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#3630 87463
  app/controllers/people_controller.rb
  app/models/parsers/xml/cv/importers/base.rb
  app/models/parsers/xml/cv/importers/family_parser.rb
  app/models/person.rb
  features/step_definitions/employee_steps.rb
  features/step_definitions/group_selection_steps.rb
  spec/helpers/insured/group_selection_helper_spec.rb
  spec/models/parsers/xml/cv/importers/enrollment_parser_spec.rb
  spec/models/parsers/xml/cv/importers/family_parser_spec.rb
  spec/models/person_spec.rb
  spec/views/insured/group_selection/new.html.erb_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#3669 87299
  app/controllers/insured/group_selection_controller.rb
  app/data_migrations/fix_ed_source_curam_cases.rb
  app/data_migrations/fix_ed_source_non_curam_cases.rb
  app/helpers/insured/families_helper.rb
  app/models/eligibility_determination.rb
  app/models/group_selection_prevarication_adapter.rb
  app/models/household.rb
  app/views/insured/employee_roles/_employment_relationships.html.haml
  app/views/insured/employee_roles/match.html.haml
  app/views/insured/families/_shop_for_plans_widget.html.erb
  features/employee/employee_passive_renewal_update.feature
  features/step_definitions/group_selection_steps.rb
  features/step_definitions/individual_steps.rb
  features/support/worlds/ivl_assistance_world.rb
  lib/tasks/create_tax_household.rake
  lib/tasks/fix_ed_source_curam_cases.rake
  lib/tasks/fix_ed_source_non_curam_cases.rake
  script/daily_eligibility_determination_change_report.rb
  script/update_eligibility.rb
  spec/controllers/hbx_admin_controller_spec.rb
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/data_migrations/fix_ed_source_curam_cases_spec.rb
  spec/data_migrations/fix_ed_source_non_curam_cases_sepc.rb
  spec/data_migrations/reactivate_tax_household_with_assistance_year_spec.rb
  spec/factories/eligibility_determinations.rb
  spec/models/eligibility_determination_spec.rb
  spec/models/household_spec.rb
  spec/script/daily_eligibility_determination_change_report_spec.rb
  spec/support/bradys_after_all.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#3658 87333
  components/benefit_sponsors/app/views/benefit_sponsors/sponsored_benefits/sponsored_benefits/new.html.slim
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#3671 86232
  app/models/mongorder.rb
  app/models/queries/family_datatable_query.rb
  app/models/queries/outstanding_verification_datatable_query.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3663 87620
  lib/tasks/creating_new_enrollment_with_reference_enrollment.rake
Labels: Mergeable: Yes, Priority: 3-High, Status: Promote to Test Environment, Tracker: Data

#3433 84402
  app/models/enrollment_shopping/affected_enrollment_finder.rb
  app/models/enrollment_shopping/enrollment_builder.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3435 84403
  app/models/enrollment_shopping/enrollment_builder.rb
  app/models/group_selection_prevarication_adapter.rb
  spec/controllers/insured/group_selection_controller_spec.rb
  spec/models/enrollment_shopping/enrollment_builder_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug
