Repository dchbx/enroll, pull requests merged in 2020-07, with the labels that each got.

#3714 88168
  app/data_migrations/expire_prior_year_ivl_active_enrollments.rb
  app/models/hbx_enrollment.rb
  app/models/services/ivl_enrollment_service.rb
  lib/tasks/migrations/expire_prior_year_ivl_active_enrollments.rake
  script/active_enrollments_in_prior_years_report.rb
  spec/data_migrations/expire_prior_year_ivl_active_enrollments_spec.rb
  spec/models/hbx_enrollment_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Promote to Test Environment, Tracker: Bug

#3711 43757
  components/benefit_sponsors/app/models/benefit_sponsors/observers/employer_profile_observer.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/observers/employer_profile_observer_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Code Refactor

#3719 88188
  app/helpers/time_helper.rb
  spec/helpers/time_helper_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3705 88088
  app/models/person.rb
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/organization.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/profiles/employers/broker_agency_controller_spec.rb
  components/benefit_sponsors/spec/dummy/app/models/person.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_forms/staff_role_form_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/organization_spec.rb
  features/brokers/create_broker_agency_staff.feature
  features/brokers/employer_broker_search.feature
  features/brokers/employer_hires_broker.feature
  features/brokers/employer_terminates_and_hires_new_broker.feature
  features/general_agencies/create_general_agency_staff.feature
  spec/controllers/employers/broker_agency_controller_spec.rb
  spec/models/organization_spec.rb
  spec/models/person_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Code Refactor

#3677 39850
  app/controllers/insured/ridp_documents_controller.rb
  spec/controllers/ridp_documents_controller_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3656 87535
  lib/tasks/hbx_reports/enrollapp_report.rake
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Code Refactor

#3699 40635
  app/controllers/concerns/vlp_doc.rb
  app/controllers/people_controller.rb
  app/helpers/config/aca_individual_market_helper.rb
  app/models/consumer_role.rb
  spec/controllers/people_controller_spec.rb
  spec/models/consumer_role_spec.rb
  system/config/templates/features/aca_individual_market/aca_individual_market.yml
Labels: Mergeable: Yes, Priority: 5-Low, Status: Accepted Pending Release, Tracker: Bug

#3731 88256
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3698 60131
  components/benefit_sponsors/app/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller.rb
  components/benefit_sponsors/app/models/benefit_sponsors/forms/benefit_application_form.rb
  components/benefit_sponsors/spec/controllers/benefit_sponsors/benefit_applications/benefit_applications_controller_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/forms/benefit_application_form_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3702 86115
  app/assets/stylesheets/employer.scss.erb
  app/assets/stylesheets/insured.scss.erb
  app/views/exchanges/hbx_profiles/_get_employer_info.html.erb
  app/views/exchanges/hbx_profiles/_get_user_info.html.erb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3688 87984
  app/data_migrations/ivl_enrollment_eligibility_report.rb
  lib/tasks/ivl_enrollment_eligibility_report.rake
  spec/data_migrations/ivl_enrollment_eligibility_report_spec.rb
Labels: Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Epic (Master Ticket)

#3690 88005
  app/views/insured/plan_shoppings/show.html.slim
  app/views/insured/plan_shoppings/thankyou.html.erb
  app/views/ui-components/v1/cards/_metal_level_select.html.slim
  app/views/ui-components/v1/cards/_reference_plan_details_shell.html.slim
  app/views/ui-components/v1/cards/_sponsor_contributions.html.slim
  app/views/ui-components/v1/cards/_sponsor_contributions_shell.html.slim
  components/benefit_sponsors/app/helpers/benefit_sponsors/registration_helper.rb
  components/benefit_sponsors/app/models/benefit_sponsors/organizations/factories/profile_factory.rb
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_applications/benefit_applications/shared/_benefit_application_fields.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/benefit_packages/benefit_packages/_sponsored_benefit.html.slim
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_benefits.html.erb
  components/benefit_sponsors/app/views/benefit_sponsors/profiles/employers/employer_profiles/my_account/_census_employees.html.erb
  components/benefit_sponsors/spec/models/benefit_sponsors/organizations/factories/profile_factory_spec.rb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/_employees.html.erb
  components/sponsored_benefits/app/views/sponsored_benefits/organizations/plan_design_proposals/contributions/_contribution_sliders.html.erb
  db/seedfiles/english_translations_seed.rb
  db/seedfiles/translations/en/cca/bootstrap_example_page.rb
  db/seedfiles/translations/en/cca/broker_agencies.rb
  db/seedfiles/translations/en/cca/buttons_panel_translations.rb
  db/seedfiles/translations/en/cca/census_employee.rb
  db/seedfiles/translations/en/cca/devise.rb
  db/seedfiles/translations/en/cca/employer.rb
  db/seedfiles/translations/en/cca/exchange.rb
  db/seedfiles/translations/en/cca/hbx_profiles.rb
  db/seedfiles/translations/en/cca/insured.rb
  db/seedfiles/translations/en/cca/layout.rb
  db/seedfiles/translations/en/cca/plan.rb
  db/seedfiles/translations/en/cca/users_orphans.rb
  db/seedfiles/translations/en/cca/welcome_index.rb
  db/seedfiles/translations/en/dc/bootstrap_example_page.rb
  db/seedfiles/translations/en/dc/broker_agencies.rb
  db/seedfiles/translations/en/dc/buttons_panel_translations.rb
  db/seedfiles/translations/en/dc/census_employee.rb
  db/seedfiles/translations/en/dc/devise.rb
  db/seedfiles/translations/en/dc/employer.rb
  db/seedfiles/translations/en/dc/exchange.rb
  db/seedfiles/translations/en/dc/hbx_profiles.rb
  db/seedfiles/translations/en/dc/insured.rb
  db/seedfiles/translations/en/dc/layout.rb
  db/seedfiles/translations/en/dc/plan.rb
  db/seedfiles/translations/en/dc/users_orphans.rb
  db/seedfiles/translations/en/dc/welcome_index.rb
  db/seedfiles/translations/en/employer.rb
  db/seedfiles/translations/en/insured.rb
Labels: Priority: 4-Normal, Status: Functional Testing, Tracker: Use Case

#3758 88816
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/forms/benefit_application_form_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#3763 88931
  app/data_migrations/update_contribution_unit_ids_on_contribution_levels.rb
  lib/tasks/migrations/update_contribution_unit_ids_on_contribution_levels.rake
  spec/data_migrations/update_contribution_unit_ids_on_contribution_levels_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#3761 88977
  components/benefit_sponsors/app/data_migrations/modify_benefit_application.rb
  components/benefit_sponsors/app/models/benefit_sponsors/services/benefit_application_service.rb
  components/benefit_sponsors/spec/data_migrations/modify_benefit_application_spec.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/services/benefit_application_service_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug
