Repository dchbx/enroll, pull requests merged in 2021-01, with the labels that each got.

#4116 91765
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/aca_shop_enrollment_eligibility_policy.rb
  components/benefit_sponsors/app/models/benefit_sponsors/benefit_applications/benefit_application.rb
  components/benefit_sponsors/spec/models/benefit_sponsors/benefit_applications/benefit_application_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#4096 88249
  app/models/services/ivl_enrollment_service.rb
  spec/models/services/ivl_enrollment_service_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#4172 92160
  components/financial_assistance/lib/schemas/common.xsd
  spec/vocabularies/common.xsd
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Promote to Test Environment, Tracker: Bug

#4095 91756
  components/benefit_sponsors/app/models/benefit_sponsors/concerns/observable.rb
  components/benefit_sponsors/app/models/benefit_sponsors/model_events/profile.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#4169 91713
  app/models/user.rb
  components/benefit_sponsors/spec/dummy/app/models/user.rb
  components/financial_assistance/spec/dummy/app/models/user.rb
  components/sponsored_benefits/spec/dummy/app/models/user.rb
  spec/models/user_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Hot Fix

#4173 92138
  app/models/census_employee.rb
  spec/models/census_employee_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#4155 92028
  app/models/transcripts/enrollment_transcript.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Data

#4048 91047
  app/helpers/events_helper.rb
  app/views/events/v2/employers/_broker_agency_account.xml.haml
  spec/helpers/events_helper_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#4119 91545
  Gemfile
  Gemfile.lock
  components/sponsored_benefits/Gemfile.lock
  components/sponsored_benefits/app/models/sponsored_benefits/services/general_agency_manager.rb
  hugo/content/docs/_index.md
  hugo/content/docs/models/general_agencies.md
  hugo/layouts/partials/sidebar-tree.html
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Support

#4195 92245
  app/views/exchanges/hbx_profiles/_view_enrollment_to_update_end_date.html.erb
  config/brakeman.ignore
Labels: Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#4189 92036
  app/assets/javascripts/dob_validation.js
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Bug

#4201 92308
  config/settings.yml
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support

#4230 92423
  app/controllers/exchanges/hbx_profiles_controller.rb
  spec/controllers/exchanges/hbx_profiles_controller_spec.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#4211 92078
  db/seedfiles/translations/en/dc/insured.rb
Labels: Priority: 3-High, Status: Accepted Pending Release, Tracker: Bug

#4216 92290
  app/helpers/portal_header_helper.rb
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support
