Repository dchbx/enroll, pull requests merged in 2021-02, with the labels that each got.

#4224 92201
  components/sponsored_benefits/app/models/effective/datatables/broker_agency_plan_design_organization_datatable.rb
Labels: Mergeable: Yes, Priority: 1-Immediate, Status: Accepted Pending Release, Tracker: Bug

#4188 92376
  components/benefit_sponsors/app/controllers/benefit_sponsors/application_controller.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3686 41527
  app/models/consumer_role.rb
  spec/models/consumer_role_spec.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Bug

#3977 90260
  app/data_migrations/update_end_date_on_invalid_tax_households.rb
  app/models/household.rb
  app/models/tax_household.rb
  lib/tasks/update_end_date_on_invalid_tax_households.rake
  spec/models/admin/aptc_spec.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Data

#4063 89874
  app/controllers/exchanges/employer_applications_controller.rb
Labels: Mergeable: Yes, Priority: 3-High, Status: Accepted Pending Release, Tracker: Support

#4194 92198
  app/data_migrations/force_publish_ben_app_reports.rb
Labels: Mergeable: Yes, Priority: 4-Normal, Status: Accepted Pending Release, Tracker: Support

#4271 92675
  app/data_migrations/bulk_census_employees_termination.rb
  app/jobs/bulk_census_employees_termination_job.rb
  lib/tasks/migrations/bulk_census_employees_termination.rake
Labels: Mergeable: Yes, Priority: 2-Urgent, Status: Accepted Pending Release, Tracker: Support
